### ISSUE TITLE
Nested Containers?

### ISSUE THREAD

**Issue by ashraffayad** [a5hik/ng-sortable#101]
Great work. Does it support nested containers? an example http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/nested
He also has the clone item feature of the right side. 
Your library is better because it works on touch devices. If only you could add these 2 features.

Thanks. Really nice work.

Ashraf

**Comment by XavierOlland** [comment]
Actually, you can do nested containers. 
The trick is to had an array containing your first level of container as an object. Then loop through it (once because you only have one result) with ng-repeat. Sofor 2 levels nested you need 3 ng-repeat.

Works OK for me.

**Comment by a5hik** [comment]
You can also see some samples here.. #15 . Thanks for your comments.

**Comment by ashraffayad** [comment]
Thanks a5hik. That exactly what I meant..

**Comment by jeevajsb** [comment]
I've added in the following manner for nested containers. It works for the outer container. But not for the inner container.


<'ul  data-as-sortable="dragListListeners" ng-model="models.lists">
<'li ng-repeat="list in models.lists | orderBy:'sortOrder' " class="separate-board-column board-column"
                ng-if="models.lists.length" data-as-sortable-item>
<'div data-as-sortable-item-handle>
<'div class="board-column-header row">
list name
<'/div>
<'ul class="board-column-cards-wrapper1 board-card-task-wrapper" data-as-sortable="dragCardListeners" ng-model="list.cards">
<'li class="board-column-cards board-card-task row" ng-repeat="card in list.cards | orderBy:'sortOrder' " ng-if="list.cards"
                            data-as-sortable-item>
                            <'div data-as-sortable-item-handle>
<'/div>
<'/li>
<'/ul>
<'/div>
<'/li>
<'/ul>
