### ISSUE TITLE
Nested Sortable (Table rows/columns)

### ISSUE THREAD

**Issue by sam0737** [a5hik/ng-sortable#104]
I have a data structure which is 2 level deep, and I would like to map it to rows, then columns of a table.  However, I can't setup a sortable on both, but just either one.

The problem is best illustrated with code.
http://plnkr.co/edit/BfglT58BSWXHxyucL595?p=preview (Everything messed up)
http://plnkr.co/edit/aUP4vaPyr1NAJtlrQChP?p=preview (Drag among columns work)
http://plnkr.co/edit/UU9lG6Cc9UTc2DKE9clX?p=preview (Drag among rows work)

**Comment by a5hik** [comment]
Just see If this helps #15
