### ISSUE TITLE
ng-sortable and angular.js 1.3.9

### ISSUE THREAD

**Issue by sundayoyeniyi** [a5hik/ng-sortable#108]
Hi

Has anyone experience using this ng-sortable with Angular 1.3.9.  I have used with and it seems not to work at all:

sample mark up

        <div class="row" id="sortable-container"">
            <div class="col-md-6">
                <div class="sortable-row" data-as-sortable="dragControlListeners" data-ng-model="itemsa">
                    <div data-ng-repeat="itema in itemsa" data-as-sortable-item="">
                        <div data-as-sortable-item-handle="">{{itema.id}}</div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="sortable-row" data-as-sortable="dropControlListeners" data-ng-model="itemsb">
                    <div data-ng-repeat="itemb in itemsb" data-as-sortable-item="">
                        <div data-as-sortable-item-handle="">{{itemb.id}}</div>
                    </div>
                </div>
            </div>
        </div>

my controler

    app.controller('TransferController', ['$scope', '$http', function ($scope, $http) {
        $scope.itemsa = [{ "id": "item a 1" }, { "id": "item a 2" }, { "id": "item a 3" }, { "id": "item a 4" }];
        $scope.itemsb = [{ "id": "item b 1" }, { "id": "item b 2" }, { "id": "item b 3" }, { "id": "item b 4" }];
        $scope.dragControlListeners = {
            accept: function (sourceItemHandleScope, destSortableScope) {return true},
            itemMoved: function (event) {},
            orderChanged: function(event) {}
        };
        $scope.dropControlListeners = {
            accept: function (sourceItemHandleScope, destSortableScope) { return false },
            itemMoved: function (event) { },
            orderChanged: function (event) { }
        };
    }]);

Kindly advise

SO.

**Comment by MaitreDede** [comment]
Have you seen #92 ?

**Comment by a5hik** [comment]
Hi I don't think this is related to any angular version problem the demo version of this library uses 1.3.8, may be this could because of #92.  hence closing this issue.
