### ISSUE TITLE
1.1.8 style update broken

### ISSUE THREAD

**Issue by oori** [a5hik/ng-sortable#112]
Please see: https://github.com/a5hik/ng-sortable/commit/c0660b204a973ef1300e2e77e8a4052c730cd7c1#diff-596435f66a27aa373c5b87d1e901e151L5
You removed style from the "mandatory style", in commit: c0660b204a973ef1300e2e77e8a4052c730cd7c1 but this display:block is mandatory for proper drag to work.

**Comment by a5hik** [comment]
Hey, thanks for pointing will update it.
