### ISSUE TITLE
Version Update Breaks Functionality

### ISSUE THREAD

**Issue by shawn-northrop** [a5hik/ng-sortable#114]
I have a project that was using version `1.1.0`. I recently ran bower and it installed version `1.1.9` which broke all functionality. I cannot select/drag my elements and I noticed that class names were not being added. (`data-sortable-item-handle` does not have the class `sortable-handle`). There were no errors in the console. I reverted back to version `1.1.0` and It is working fine.

**Comment by a5hik** [comment]
it is renamed to prefix with 'as-'  to the directives. like 'as-sortable', 'as-sortabel-item' & 'as-sortable-item-handle'
