### ISSUE TITLE
Binding to is-disabled is not working

### ISSUE THREAD

**Issue by lucenty** [a5hik/ng-sortable#115]
http://plnkr.co/edit/tX4GBZy7UOFNi8rc7ACq?p=preview

This code is showing that binding scope value to is-disabled is not working.

If you manually change $scope.isEditingLayout, it will work.

If you press button to turn change this value, the sortable behaviour 
doesn't change.

**Comment by abasic** [comment]
http://plnkr.co/edit/iG1X0t8LMYqNCJ4ArpXr?p=preview

You need to pass the parent scope variable to 'is-disabled' not wrap it in curly braces (in your example it is 'isEditingLayout' not {{ isEditingLayout }}).

**Comment by lucenty** [comment]
It work, thanks! 
Sorry, I was then at the beginning of learning AngularJS.
