### ISSUE TITLE
Dragging style

### ISSUE THREAD

**Issue by sn0rcha** [a5hik/ng-sortable#117]
Heya,

Thanks for an awesome plugin!

I was just wondering if there was any way to actually style the item you are dragging when dragging it. Currently it puts the bullet point to the left and has a grey border and adds some padding up the top while dragging. I'm using the following css:

.as-sortable-item { width: 100%; margin: 2px; border: 1px solid #eaeaea; border-radius: 5px; list-style: none; }

Many thanks!

**Comment by twmulloy** [comment]
Try setting your css definitions within `.as-sortable-drag`. Where `.as-sortable-drag` is the cloned parent list for dragging.

For example if this is your original element
```
<ol class="as-sortable">
  <li class="as-sortable-item">
    <a class="as-sortable-item-handle">Item 1</a>
  </li>
  <li>
    <a class="as-sortable-item-handle">Item 2</a>
  </li>
</ol>
```

When dragging `Item 1` your  `.as-sortable-drag` element it creates this as the draggable element (you want to style this)
```
<ol class="as-sortable-drag">
  <li class="as-sortable-item">
    <a class="as-sortable-item-handle">Item 1</a>
  </li>
</ol>
```

**Comment by hernancete** [comment]
Hi, thanks for this awesome library.

I was wondering if it is possible to apply differents styles to the dragging item when it is over different lists (sortable lists). I have a list with all the items and a little list acting as a trash, so I want the dragged item becomes red when it's over the trash. It that possible? The trash is a div with fixed positioning.

Thanks in advance.

**Comment by a5hik** [comment]
@hernancete yes you can do this, there is a callback exposed ..after you sort (order changed) and move (item moved) you just need to implement and apply the CSS. Just refer the samples provided for the callback details.

**Comment by hernancete** [comment]
Thank you very much for the quick response.
May be I expressed in a wrong way, but I need to apply an style to the drag item (as-sortable-drag) when it is over a list (trash) but before drop it. (Pretty much the same as when you remove an app from the desktop in an android device, that appears the remove icon above in the screen.)
Anyway, the solution it seems to be a matter of CSS, not this library.
If it is a way of doing this with callbacks, please let me know.
Thank you again.

**Comment by mrchacon** [comment]
Hi! I'm having a problem with the dragging class. The doc says when an item it's been dragged a class ("as-sortable-dragging") is added to the as-sortable-item container. But in my case when an item is in drag state the html li tag is replaced by 2 li containing the placeholder and a "sortable-hidden" and obviously my custom as-sortable-dragging class is not being applied.

Any ideas? thanks!

Here's my as-sortable for reference:

<pre><code><ull class="cards card-list" as-sortable="aux.sortOptions" ng-model="aux.groupedEntries[state.key]">
				<li class="card" ng-repeat="entry in aux.groupedEntries[state.key]" as-sortable-item="">
					<div class="clearfix agile-posts" as-sortable-item-handle="">
						<div
							post-entry="entry"
							current-user="currentUser"></div>
					</div>
				</li>
			</ull></code></pre>

**Comment by nickwq** [comment]
@mrchacon The element you are dragging is out of your list hierachy, make sure your styling code is applied to correct scope.
