### ISSUE TITLE
Drop anywhere out of the list doesn't call any callbacks and moves to last position a placeholder was set

### ISSUE THREAD

**Issue by mritzco** [a5hik/ng-sortable#121]
To replicate:
- Start drag
- Move down ( a placeholder will be set somewhere in the list)
- Move away from the list and drop the element.

In this case I would like to cancel the move but I don't get any of the callbacks called, accept function is not called and orderChanged contains the destination where the placeholder was set
Is there anyway in which I can check and cancel the move? 
Thanks!

**Comment by a5hik** [comment]
@mritzco this again depends on the requirement, currently the library is written to drop the item in to a place holder if a place holder is visually present. 

the drag cancel can be performed by pressing 'Esc' key. this is just to let you know the library is having the implementation in place, but it is up to us when to invoke it. It just requires a bit of a tweak.

**Comment by mritzco** [comment]
Hi @a5hik 

I'm really sorry I didn't answer before (and no need to reopen the issue unless you consider it worth exploring), the case for this is for devices where 'Esc' is not available, so every phone, tablet and touch screen device pretty much could benefit from an 'automatic' cancel event if implemented.
I myself, find a bit hard to remember to hit esc when I'm using the mouse for dragging yet I'm accustomed from my OS that the drag will be cancelled if dropped on a non-valid target.

Having the drag cancel event is more than half way there, perhaps the missing part is where to respond / detect a drop outside valid placeholder. If you could give me a hint I can get into the code and give it a try.
Thanks!
