### ISSUE TITLE
Drop item on adjacent (sibling) list item instead of inserting into list?

### ISSUE THREAD

**Issue by twmulloy** [a5hik/ng-sortable#123]
Is there a way, or what would be the best approach to accomplishing this? 

If you have two adjacent lists of items, and you drag an item from list 1 to an item in list 2 within a certain footprint size (of the drop on item) be able to drop the item onto the item instead of inserting it into the adjacent list.

Here is what I have, it's not quite there

```
## Allowed movements
accept: (sourceItemHandleScope, destSortableScope, destItemScope) ->

  if destItemScope            
    rangeTop = destItemScope.element.offset().top
    rangeBottom = rangeTop + destItemScope.element.height()
    handleTop = sourceItemHandleScope.itemScope.element.parent().offset().top
    inRange = (rangeTop < handleTop and handleTop < rangeBottom)
    if inRange
      destSortableScope.element.find('li.as-sortable-placeholder').remove()
      return false
  
  true
```

**Comment by twmulloy** [comment]
An easier way to put it-- is there a way to make an item sortable (draggable) + droppable?

**Comment by a5hik** [comment]
with the clone option this should be possible, hence closing this.
