### ISSUE TITLE
List is not rendered on $scope.apply()

### ISSUE THREAD

**Issue by jishi** [a5hik/ng-sortable#124]
I managed to get this to work if the data is already available when the template is rendered. However, I receive data asynchronous through socket.io, and broadcast an update on the scope, which I listen to like this:

    $scope.$on('update', function (event, data) {
      console.log('captured update', data)
      $scope.x = data.menu.items;
      $scope.$apply();
    })

However, this does not trigger a render of the menu, like a regular ng-repeat does. Is there any way to trigger the as-sortable manually, or make it apply changes on external updates like this?

**Comment by Fearful** [comment]
I'm having the same issue, using socket.io to update the items inside ngSortable, it doesn't seem to work neither calling $apply or calling $digest directly.
The digest cycle triggers but it seems to ignore the changes done to the scope, so the view remains the same
