### ISSUE TITLE
Move all items from one list to another.

### ISSUE THREAD

**Issue by ryanray** [a5hik/ng-sortable#125]
If the user wants to move all items to another list I would like to have a button so they don't have to drag each item individually.

I have it working just by moving the items in to the other array but then things get out of sync because I get this error when dragging items after the move: "Uncaught HierarchyRequestError: Failed to execute 'appendChild' on 'Node': The new child element contains the parent."

Seems like this would already be available, I just didn't see it mentioned in the docs.

**Comment by a5hik** [comment]
right now this feature is not available.
