### ISSUE TITLE
Question - Is there any way to constrain the drag area?

### ISSUE THREAD

**Issue by AlbertSanIza** [a5hik/ng-sortable#129]
Hello, I have been working with this module and its awesome! :+1: 

The thing is that I am doing a single page web app and I don't want the scroll bars to appear in any state of the app.

The problem happens when I drag the items near the down-right edge of the screen:
![image](https://cloud.githubusercontent.com/assets/3300602/6654156/78457462-ca6f-11e4-9e86-2039f19a60bb.png)

and the bars appear.
This problem does not occur on the upper-left side of the browser, and I am not sure why.

(sorry for the bad English)

**Comment by a5hik** [comment]
Hi looks like the CSS on the wrapper is causing this. but nothing to fix it on the library itself.

**Comment by AlbertSanIza** [comment]
Yeah, i am not really sure why it happened, because I am not very familiar with CSS.

I manage to use use the CSS from your advanced demo. Its pretty awesome.

thanks! :+1:

**Comment by a5hik** [comment]
sure, thanks. let me close this.
