### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by kentcdodds** [a5hik/ng-sortable#130]
Want to use this with webpack via npm. The current version on npm is 0.0.3. Could you publish an update please?

**Comment by kentcdodds** [comment]
Just noticed [the version on npm](https://www.npmjs.com/package/ng-sortable) is not yours, but someone else's. Could you please publish your library to npm? Thanks!

**Comment by a5hik** [comment]
ah.. someone got the name on npm.. !! you can do a bower install.

**Comment by kentcdodds** [comment]
I know I can do a bower install. But my project is using npm and I'd prefer to only have one package manager in my project. If the name matters that much to you, perhaps @keyvanfatehi would be willing to give it up. [The repo](https://github.com/keyvanfatehi/ng-sortable) isn't even there anymore. @keyvanfatehi would you be willing to unpublish your package in favor of @a5hik's?

**Comment by keyvanfatehi** [comment]
will do

**Comment by keyvanfatehi** [comment]
@a5hik @kentcdodds 

name released1

**Comment by kentcdodds** [comment]
Thanks @keyvanfatehi! :-D

**Comment by a5hik** [comment]
Thanks @keyvanfatehi ., @kentcdodds it is published now.

**Comment by a5hik** [comment]
https://www.npmjs.com/package/ng-sortable

**Comment by kentcdodds** [comment]
Thanks @a5hik!
