### ISSUE TITLE
Load from $http or adding items after timeout fails

### ISSUE THREAD

**Issue by pepperlk** [a5hik/ng-sortable#138]
See plunker for repro steps
http://plnkr.co/edit/CH4Wyfdk2djakTDua1DS?p=preview

**Comment by pepperlk** [comment]
Spent a bit trying to track this down. The scopes are losing track of the ngModel will come back to it later.

**Comment by paulsouche** [comment]
Hi,

Same issue here in cause line 406 of ng-sortable.js

```javascript
  // Set the model value in to scope.
  ngModel.$render = function () {
    //set an empty array, in case if none is provided.
    if (!ngModel.$modelValue || !angular.isArray(ngModel.$modelValue)) {
      ngModel.$setViewValue([]);
    }
    scope.modelValue = ngModel.$modelValue;
  };
```

Do not setViewValue with an empty array and it'll work like a charm

**Comment by a5hik** [comment]
PR #143 is merged, hence closing this issue. thanks @paulsouche for the PR.
