### ISSUE TITLE
Access to replaced element's  model?

### ISSUE THREAD

**Issue by nitro52** [a5hik/ng-sortable#140]
How can i get access to the model of the element that you have dropped the item on to?
i know what the index was via 

event.dest.index

but all the collection i can find event.dest.sortableScope.modelValue or event.source.sortableScope.modelValue are both the same and are the updated version of the array. So the dest.index matched the item i am dragging not the one i replaced.

**Comment by a5hik** [comment]
@nitro52 right now the model of the replaces items are not exposed. Can you better explain the use case so that I can see If it can be achieved on other way.

**Comment by nitro52** [comment]
The model contains a rank that i need to access so i can make a call to the API and update the position. The value of the rank does not match the index of the javascript array so i can't use event.dest.index

for now i have had to try to guess the new index of the old item. dest.index + 1 but this has messy edge cases like it should be -1 at the end of the list and + 0 if there is only one item

**Comment by a5hik** [comment]
Hi Just copy the destSortableScope array in to a new var. and remove the dest.index and the new item in the dest.index is the original item.

For example, You have the original sortable array of size [0-4] you are inserting in to position 1. now the array becomes size [0-5]. now copy the array in your callback. remove the item in position 1 (dest.index). it become [0-4]. the original item should be there in position 1 now.

**Comment by a5hik** [comment]
in case of additions in the end its going to return undefined. original [0-4] adding in the end becomes [0-5] and the index is 5. when you remove the 5th indexed item. it again becomes [0-4] and getting the arry[5] returns undefined, meaning there are no original item there it is an insert at the end. hope this helps.
