### ISSUE TITLE
can't use ng-sortable with debugger info disabled

### ISSUE THREAD

**Issue by orisust** [a5hik/ng-sortable#144]
hi,
if i disable the debugger info (  $compileProvider.debugInfoEnabled(false); )
the library doesn't work, because it cannot find the scope of the DOM element - got undefined

here is the same problem - https://github.com/angular/angular.js/issues/9515
and they fix it

**Comment by steve-tapley** [comment]
+1

**Comment by iojohnso** [comment]
+1

**Comment by JasonMore** [comment]
I was just going to create a new comment with this but @orisust already made it, thanks! :+1:  Here is a plunkr with it being broken in case you need it http://plnkr.co/edit/KhVqiP?p=preview 

Offending code:
```
// this breaks ng-sortable
// https://docs.angularjs.org/guide/production#disabling-debug-data
app.config(['$compileProvider', function ($compileProvider) {
  $compileProvider.debugInfoEnabled(false);
}]);
```

**Comment by czterocyty** [comment]
+1

**Comment by pbassut** [comment]
+1

**Comment by oori** [comment]
FYI:    until (and if) this is pulled into the master branch.    you can use this branch:  https://github.com/oori/ng-sortable#fix-144    ```bower install oori/ng-sortable#fix-144```
I use it on production since a week.
