### ISSUE TITLE
Drag and drop between two ng-sortables is broken in latest commits

### ISSUE THREAD

**Issue by longzheng** [a5hik/ng-sortable#149]
Commit 3318e40e738ff7bc8972201685d1765caec0306d has broken drag and drop between two ```ng-sortable``` elements because it overrides the ```targetElement``` with the ```source``` element.

https://github.com/a5hik/ng-sortable/commit/3318e40e738ff7bc8972201685d1765caec0306d#commitcomment-10984165

**Comment by a5hik** [comment]
@longzheng thanks for pointing will look in to it.

**Comment by longzheng** [comment]
We're going to patch this in our own version by adding an options that allows us to disable
```targetElement = angular.element(placeElement).parent();```

**Comment by a5hik** [comment]
the broken commit is reverted. things are back to normal.

**Comment by longzheng** [comment]
@a5hik I would add though the patch was necessary to fix the sorting behavior for ```table``` while using a ```<tbody>```.
