### ISSUE TITLE
Text on dropped item is annoyingly selected (marked), does not happen in Chrome.

### ISSUE THREAD

**Issue by morfin** [a5hik/ng-sortable#153]
Hi,

You can try with Firefox or Safari:
http://a5hik.github.io/ng-sortable/plunker.html

Drag and drop an item, you will notice the text is selected (marked). 

This problem does not happen in Chrome.

How can I avoid this ? Thanks.

**Comment by stripathix** [comment]
You can create a directive with following function

document.onselectstart = function() { return false; }
document.onmousedown = function() { return false; }

Example :+1: 
angular.directive('disableHighlight', function() {
  return {
    restrict: 'A',
    link: function (scope, element) {
      element[0].onselectstart = function() { return false; }
       element[0].onmousedown = function() { return false; }
    }
  };
});

Now use this 'disable-highlight' directive on parent container.

**Comment by morfin** [comment]
Works perfect. 

Thanks a lot.
