### ISSUE TITLE
Reorder using orderBy and trackBy

### ISSUE THREAD

**Issue by mrchacon** [a5hik/ng-sortable#154]
When I add orderBy or trackBy and make a drag of item1 the dropped item is the item above of item1 in vertical containers.

Any help?

Thanks

**Comment by a5hik** [comment]
Hi as the sortable does its own ordering, the orderBy filters wouldn't work well, you need to implement your custom logic be it order by or any . in the callbacks eg. orderChanged, itemMoved.
