### ISSUE TITLE
Drop fails with empty lists and to drop at bottom of the list.

### ISSUE THREAD

**Issue by a5hik** [a5hik/ng-sortable#158]
Mikhael reported me that 

"looks like once the list is empty in the demos, you cannot drag the items back to it. 
I thought it's because <ul> 's size becomes 0, but even after I forced it to some min val, I still can't drag items to an empty list.
Is it a bug or is there a setting I need to enable?"

It is a bug introduced by commit https://github.com/a5hik/ng-sortable/commit/3cfc2f005395fcbe356fa9e7ad67d85d1a598b07 .

**Comment by wk-cof** [comment]
Thanks for the quick fix!
