### ISSUE TITLE
Question about destItem param in accept callback

### ISSUE THREAD

**Issue by zman13** [a5hik/ng-sortable#159]
I am trying to intercept the current dragging activity so I can tell if the current placement of a drop is acceptable or not based on business rules. I am having a problem using code like this 

        function accept(sourceItemHandleScope, destSortableScope, destItem) {
            if (destItem) {
                console.log(destItem.index());
             }

because it seems that destItem.index() acts differently when moving at the begining and end of a list. My goal is to be able to at recreate what the dest will look like if the user was to drop it at any given point. What would be the best way to be able to see what the affected destSortableScope.modelValue would look like ?(the current destSortableScope.modelValue is the unaffected one)
Thanks
Marc

**Comment by a5hik** [comment]
@zman13 I had some pointers given on #140 ., Plz see If that helps. or it is related anyways.
