### ISSUE TITLE
1.2.2 is not published to npm

### ISSUE THREAD

**Issue by llwt** [a5hik/ng-sortable#164]
The most recent updates haven't been pushed to npmjs, the current version on there is [1.2.0](https://www.npmjs.com/package/ng-sortable).

**Comment by oori** [comment]
it is there.  you can close this issue.

**Comment by llwt** [comment]
@oori You sure? Am I looking at the wrong project?
![ng-sortable](https://cloud.githubusercontent.com/assets/1036428/7854194/0150b992-04cc-11e5-98f4-33f102d1415f.png)

**Comment by oori** [comment]
Try ```bower info ng-sortable```  you should see 1.2.2 listed.  don't you?
also:  ```bower info ng-sortable#1.2.2```

**Comment by llwt** [comment]
@oori I'm talking about the [NPM registry](https://www.npmjs.com/), not bower.

**Comment by oori** [comment]
@llwt you are right,  sorry.  
@a5hik You need to ```npm publish```

**Comment by a5hik** [comment]
Will do it for sure. @llwt @oori thanks for reminding.

**Comment by a5hik** [comment]
Its Done!

**Comment by llwt** [comment]
@a5hik Awesome, thanks!
