### ISSUE TITLE
Disabling items from list based on runtime condition

### ISSUE THREAD

**Issue by wormyy** [a5hik/ng-sortable#166]
How can I prevent only some list items from being dragged based on a condition that can change at runtime?

**Comment by a5hik** [comment]
Hi the 'is-disabled'  can be applied at sortable list level.

and If you want only certain items then look for applying 'no-drag' on those items.

**Comment by bradgreens** [comment]
I've been trying to disable my items as well. I'm on ng-sortable 1.2.2, and when a condition is met I try to disable the list with the following:

```
      $scope.$watch( 'question.isSaved', ( myCondition ) => {
        if( myCondition ) {

          $element.find( '[as-sortable]' ).attr( {
            'is-disabled': true,
          } )

          $element.find( '[as-sortable-item]' ).attr( {
            'is-disabled': true,
          } )

          $element.find( '[as-sortable-item-handle]' ).attr( {
            'is-disabled': true,
          } )
        }
      }  )
```

The attributes get set, but nothing gets disabled. And I realize the documents only refer to the `[as-sortable]` element. I can watch it in the debugger and it seems I'm missing something. Do you have an easy code example to disable the sortable list after the user has interacted?

**Comment by bradgreens** [comment]
I've spent a couple rounds of effort trying to disable an initialized `as-sortable` list and it's respective directives (`as-sortable-list`, `as-sortable-handle`) but I can't get it. Would it be much trouble to provide a fiddle?

**Comment by bradgreens** [comment]
My conclusion is that assign the attribute `is-disabled="true"` does not work dynamic, rather it only works when the directive is first parsed. Ideally, this angular module would leverage the `ng-disabled` attribute to disable the list, and it should work at any time "on the fly".

**Comment by FoolsRwe** [comment]
My conclusion is that assigning the attribute is-disabled="true" does not work dynamicly, rather it only works at the time the directive is first parsed.

I am having this same issue, it's pointless having it in the module if it does not work.

**Comment by bradgreens** [comment]
@FoolsRwe I was able to figure this out in my application. The documentation is mis-leading, the correct way to use the `is-disabled` attribute is to pass in a Javascript object with a boolean property of `true`/`false`. In my application, the solution looks like this 

    `<div class="question-answers" ng-model="question.question_answers" as-sortable="sortableOptions" is-disabled="question.isSaved"></div>`

**Comment by a5hik** [comment]
this is fixed in the readme.
