### ISSUE TITLE
Drag the table rows and the row goes to the bottom of the table.  

### ISSUE THREAD

**Issue by josietam** [a5hik/ng-sortable#167]
![animation](https://cloud.githubusercontent.com/assets/10356804/7930330/0bfbb15e-093a-11e5-9113-15eb809c9a57.gif)

Refer to the gif, i drag the row of "a".  While i was dragging it, this row appears at the bottom of the table until finish the dragging process.

Besides, the width of the table cell also expands while i was dragging.  Can i ask if you have any idea?
Thank you!

**Comment by a5hik** [comment]
Hi while, dragging an item the CSS of its parent cell is applied the Drag element. that is causing you this issue.

I was not sure for some reason we are adding the class of the sortable element also in to the drag element. 

dragElement.addClass(scope.sortableScope.element.attr('class')).addClass(sortableConfig.dragClass);

You could override any CSS of sortable element via setting the dragClass.

Let me also see whether I can remove applying the sortable class to the drag element.

**Comment by a5hik** [comment]
You need to see any of your  CSS of sortable class is causing this? 
also we apply the height and width of the element in itemScope to the drag element. 

Should be a CSS issue.

**Comment by a5hik** [comment]
support for table drag is added as part of #237 hence closing this.
