### ISSUE TITLE
Is is possible to drop in a "copy" instead of the real item

### ISSUE THREAD

**Issue by ajmajma** [a5hik/ng-sortable#170]
I am trying to have the effect of drag and drop from one list to another with out removing/re-ordering the item from the first list, almost like as if it were taking a copy from the first list instead of using the actual item. Is this possible with your library? Thanks!

**Comment by ianbelcher** [comment]
Hi @ajmajma.

I'm not sure if this will work in your case, but I managed to do this by using a hardcoded reference on the first list. Its a bit of a hack and will only work if you have a known, static number of original items. My repeated objects in each list are just ids which are then fed into a directive for the ui. Basically:
```
<li data-ng-repeat="id in [1,2,3,4,5,6,7,8,9,10,11,12,13] track by $index" data-as-sortable-item>
  <div data-as-sortable-item-handle>
    <symbol id="{{id}}"></symbol>
  </div>
</li>
```
You will be able to drag any of these objects out of that list and they will reappear, and the list will always be in order. Using id's will get you into trouble with dupes so your other lists should look something like:
```
<li data-ng-repeat="id in lists.list1 track by uniqueTrackingKey()" data-as-sortable-item>
    <div data-as-sortable-item-handle>
        <symbol id="{{id}}"></symbol>
    </div>
</li>
```
And adding the uniqueTrackingKey to you controller:
```
$scope.uniqueTrackingKey = function (index, id) {
    // If you're using uuid this is a good use case, otherwise just generate a large range
    //return uuid4.generate();
    return Math.random() * 100000;
};
```

If your first list is actually dynamic, another strategy could be to add a $watch on the variable within the controller and rewrite the variable any time it changes? Not sure if this would work though.

**Comment by Liujianfu** [comment]
I made some changes to the code, now I can drag a copy (clone) of the source item to destination container.

**Comment by delachi** [comment]
@Liujianfu Where an I find the code/how-to on how to implement dragging a copy(clone)?

**Comment by Liujianfu** [comment]
you can find it at https://github.com/Liujianfu/ng-sortable
 
Date: Wed, 17 Jun 2015 17:17:08 -0700

**Comment by a5hik** [comment]
the clone option is available as part of the core lib hence closing this.
