### ISSUE TITLE
Protractor Tests Not Working

### ISSUE THREAD

**Issue by mrowles** [a5hik/ng-sortable#178]
Hi,

We cannot simulate a dragAndDrop / mouseDown + mouseMove + mouseUp on the sortable items. Instead of grabbing the item, the text just gets highlighted instead. We've tested on a number of browsers, targeted various elements and also hacked some coordinates together to no avail.

I noticed there are no current e2e tests for the module currently, are you planning on adding support for this in the future? Happy to contribute, but the above issue currently stands.

Cheers

**Comment by a5hik** [comment]
@mrowles writing test cases is good, If you wish to contribute please do so.  I was thinking to add karma tests.

**Comment by mrowles** [comment]
I would gladly, but it seems like the issue is karma and being able to drag
and drop the draggable objects using the protractor methods.

**Comment by a5hik** [comment]
Ok, Protractor tests would be fine.
