### ISSUE TITLE
Flickering during drag

### ISSUE THREAD

**Issue by JohannesAtGit** [a5hik/ng-sortable#18]
I am trying to implement your great library in my project.

The problem is:
Sometimes if I drag an element, the preview free space is flickering between two states. It seems your directive is not sure, where to show the drop preview.

Unfortunately I can't reproduce this issue with your examples.
The examples always work fine.

Do you have a idea, what the problem might be? Could something in the CSS cause the problem?

**Comment by hirelee** [comment]
@a5hik Great project, @JohannesAtGit is correct in a sense with the flickering. This seems to only occur when each sortables items are not the exact height. I encountered this issue when moving  a div with a height of 100pixels whilst the others are 500+ . Let me know your thoughts.
