### ISSUE TITLE
Documentation or functionality fix for placeholder.

### ISSUE THREAD

**Issue by artgryn** [a5hik/ng-sortable#182]
Docs quite pure and does not gives all functionality description. My bottleneck with placeholders. According to docs its possible to add some placeholder modification but only documentation for addition placeholder classes present in the docs(or I just didn't manage to find it?). 

Also it says that it should be possible to modify placeholder to use some template but no documentation/examples/demos(or docs doesn't not complete or functionality missing). I found some way to add template but it seems buggy. 

Also I think there some problems when you using not a UL -> LI drag-and-drop structure.

P.S. if docs not complete, I can help with that.

**Comment by a5hik** [comment]
@artgryn If you think you can add more details, please do so. contributions are welcome.

- Ashik
