### ISSUE TITLE
Item list changed before orderChanged triggered 

### ISSUE THREAD

**Issue by asolimaan** [a5hik/ng-sortable#183]
HI, I have Order property for each item; changed when item moved, then sync the change to the server.
As you see here  http://plnkr.co/edit/wKDy3meQvFoMSlrO91tK?p=preview  (Try randomly reorder the list many times)
You will notice that the order duplicated and some items override others item in the list. It cause duplicates in the repeater  and dismiss the order.  
is this known issue or i do it wrong?

**Comment by a5hik** [comment]
@asolimaan You need to remove the filter orderBy: 'Order', why do you need this? don't you need to retain the order that you dragged.

**Comment by asolimaan** [comment]
Yes i need to retain the order i dragged, but i need to save that order too in db to show the list in other pages with same order, in addition i want to add label before the item to show its new Order after dragging.  
I updated plunkr to simulate my case exactly after remove Order filter. 
The exceptions is gone but the list still not ordered.
http://plnkr.co/edit/wKDy3meQvFoMSlrO91tK?p=preview 
my use case as follow :
1) First item
2) Second item
3) Last Item  
after moving last item to the top, it becomes:
1) Last Item
2) First Item
3) Second Item
