### ISSUE TITLE
Dragging a disabled dropdown

### ISSUE THREAD

**Issue by dreamerkumar** [a5hik/ng-sortable#186]
I can drag a select tag when it is not disabled. It looks messy though as on click of it, the drop down expands. This is something I do not want while dragging.

When I disable the dropdown, I cannot drag it. I am able to drag other form controls that are in disabled status. 

Could there be an easy fix to make it work for disabled select tags. Any workaround for this?

**Comment by a5hik** [comment]
you just need to set the 'no-drag' attribute. plz refer the docs.

**Comment by dreamerkumar** [comment]
I do need to drag the dropdown. It's just that I am not able to if I add the disabled attribute to the select tag.
In short, I want to drag a disabled dropdown but I can't. I am able to drag disabled textboxes and other fields.

**Comment by a5hik** [comment]
this could be a generic problem, the plugin doesn't do anything specific to field types. I'm not sure how can you help on this.

**Comment by dreamerkumar** [comment]
You are right. Once I add the disabled attribute to the select element, the mouse events for that element does not get raised. Nothing you can do if the flow never reaches the listeners in this plugin. We can close this issue. Thanks for responding to my query. And thanks for creating this for us!!
