### ISSUE TITLE
Disable certain elements in list

### ISSUE THREAD

**Issue by omarw** [a5hik/ng-sortable#188]
Is it possible to conditionally disable some elements in a list from being dragged and from being dragged over. Maybe like an as-sortable-item="false"?

**Comment by a5hik** [comment]
Hi there is a 'accept' callback you need to implement for - being dragged over. see the sprint example on the demo.

To disable drag itself, haven't tried my self.. But to disable the entire list there is a 'isDisabled' attribute you can assign at runtime.. If it is for specific elements then may be you can try implementing the 'dragStart' callback.

**Comment by omarw** [comment]
I put an ng-if on the 'as-sortable-item-handle' element. That seems to help.
