### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by HHogg** [a5hik/ng-sortable#193]
While I completely agree with the module name change :) .... putting it as a [PATCH release] (http://semver.org/) is going to cause a lot of apps to fail to load (like with ours now) when bower automatically pulls down the latest version during someones deployment ... a module name change is not just a module breaking change but an application breaking change. 

Maybe should probably be a MINOR if not a MAJOR release?

**Comment by pedrosanta** [comment]
:+1: 

Yeap, if we went all semver strict about this, it could be considered stuff for a MAJOR release yes, as per http://semver.org:

> 2 . MINOR version when you add functionality in a backwards-compatible manner

This should, *at least*, have been a new MINOR release (`1.3.x`), so folks using "~1.2.2" or "1.2.x", the bower default by the way, won't get completely slap-faced by this.

**Comment by a5hik** [comment]
I too agree, let me release a 1.3.0 version.

**Comment by a5hik** [comment]
Released two versions

1.  1.2.3 with module name as 'ui.sortable' and 
2.  1.3.0 with module name as 'as.sortable'

Both available in bower & npm.
