### ISSUE TITLE
Draggable from A to B, but not B to A

### ISSUE THREAD

**Issue by Raker** [a5hik/ng-sortable#194]
First things first, great library. Really appreciate the time put in to develop it and that it doesn't use jQuery. Primary reason I chose to go with this library.

I'm looking to implement some functionality that allows you to drag an item from Column A to Column B, but not Column B to Column A.

I figured it had something to do with this code:
```
accept: function (sourceItemHandleScope, destSortableScope) {
  return sourceItemHandleScope.itemScope.sortableScope.$id === destSortableScope.$id;
}
```

But I'm having a hard time understanding exactly what the return statement line of code does, or how I'd manipulate accept to perform the functionality I'm looking for.

Any help would be appreciated. Not a huge deal if it's not possible, as this is a pretty specific nuance. Thanks!

**Comment by a5hik** [comment]
Hi basically u get the source and destination sortable scope.

And based on that you can define the movement of the items.

Sortable scope is the scope of sortable container.
You just need to implement the logic in the 'accept' method to control the drag. Let me know if u need help.

**Comment by ValentinH** [comment]
It would be cool to be able to give an id or a tag ('A' and 'B' for instance) to a sortable object and then to be able to test easily in the accept function if the source is 'A' or 'B'.

Currently, I do this by adding an id attribute to the `$scope.dragControlListeners` object and then testing like this in the accept function:
```js
accept: function(sourceItemHandleScope, destSortableScope) {
    var source = sourceItemHandleScope.itemScope.sortableScope.options.id,
        destination = destSortableScope.options.id;
    
    if(source === 'A' && destination === 'B') {
        // A -> B logic here
    }
    else if(source === 'B' && destination === 'A') {
        // B -> A logic here
    }
    return true;
    
}
```
But this is quite ugly...

Is there currently an easier way to do this?

**Comment by a5hik** [comment]
@ValentinH just give the sortable element an id. and get the element from the sortableScope. and check for the id.

**Comment by ValentinH** [comment]
What is the sortable element? Is it the object I bind to the `data-as-sortable` attribute?

**Comment by a5hik** [comment]
Yes

**Comment by ValentinH** [comment]
So what is the difference with the code I provided above?

Le mar. 4 août 2015 19:39, Muhammed Ashik <notifications@github.com> a
écrit :

**Comment by a5hik** [comment]
The Id I was referring is more of adding a html attribute element Id. And the logic is independent of the sortable directive.

**Comment by ValentinH** [comment]
OK I got the idea. However, this means that I have to manipulate the DOM inside my controller to get the ID and it doesn't feel good!

**Comment by wonskarol** [comment]
@ValentinH,

I'd like to achieve the same behavior (move only from A to B). Could you post here your solution? 
I don't get the idea described by @a5hik:

> @ValentinH just give the sortable element an id. and get the element from the sortableScope. and check for the id.

**Comment by a5hik** [comment]
@wonskarol the idea is simple . 

1. Give an id to the sortable element. say divA and divB.
2. Implement the accept callback, check for the destSortableScope id and then do the validation.
3. If you don't allow drop return false else true.
