### ISSUE TITLE
My personal opinion for ng-sortable.style.css

### ISSUE THREAD

**Issue by EricMcRay** [a5hik/ng-sortable#195]
if "ng-sortable.style.css" is optional can you remove that from bower's main files? Because I use grunt with wiredep, it puts that css file everytime I serve from grunt and it breaks my css.

**Comment by a5hik** [comment]
Yeah, its a valid point.let me modify this.

**Comment by a5hik** [comment]
@EricMcRay modified this in the master copy, let this be included in next release.
