### ISSUE TITLE
Working with bootstrap's columns

### ISSUE THREAD

**Issue by piernik** [a5hik/ng-sortable#198]
How to make Your plugin work with bootstrap columns?
Here is example:
http://plnkr.co/edit/OOBt5QLt1HQ9qDCiSKqu?p=preview

Placeholder is always in top left corner, can't move item 5 between 3 and 4.

I have `containerPositioning:'relative'`

**Comment by nicolaje** [comment]
I am interested in this too.

**Comment by a5hik** [comment]
are you trying to achieve horizontal sorting.. then please look at.

http://plnkr.co/edit/OcaMzBV3c0K3CL1nw9L4?p=preview

**Comment by nicolaje** [comment]
Thanks for your answer but for me, the question would more be to have this kind of gallery:
http://ironsummitmedia.github.io/startbootstrap-thumbnail-gallery/#
sortable

**Comment by a5hik** [comment]
@nicolaje this should be possible, you can make the columns as sortables. Its just the default sorting. you can do the same like the demo pages.
