### ISSUE TITLE
ng-sortable in bootstrap modal dragging object miss placed

### ISSUE THREAD

**Issue by mkashifkhan** [a5hik/ng-sortable#199]
Hi,
I am showing a list in bootstrap MODAL,  it works fine, but it shows the drag image 
 at wrong position, it goes out of the screen, anyone knows the solution? 
thanks

**Comment by franklinjavier** [comment]
+1

**Comment by ibhi** [comment]
@mkashifkhan 
Did you find a fix for this issue?

**Comment by franklinjavier** [comment]
Try to use 
```
vm.dragModel = {
      containment: '.modal-content-inner',
      containerPositioning: 'relative'
};
```

**Comment by bayanAbuawad** [comment]
Thanks, @franklinjavier , that solved the problem for me.
