### ISSUE TITLE
Bootstrap Cols Breaking ng-sortable on iPad Safari

### ISSUE THREAD

**Issue by johnbrunnings** [a5hik/ng-sortable#209]
Hey All,

***To TEST you must use Safari on iPad***

This can easily be demo'd using ng-sortable's own demo pages - 

Simple:
http://a5hik.github.io/ng-sortable/plunker.html
Advanced:
http://a5hik.github.io/ng-sortable/

Both no longer work on iPad Safari, but did until recently.

Further you can see this still works using the referenced horizontal sorting plnkr on iPad Safari:
http://plnkr.co/edit/OcaMzBV3c0K3CL1nw9L4?p=preview

This does not contain Bootstrap Cols and thus works.

Finally, if Bootstrap Cols are on only the items themselves, but *not* on any parent element, ng-sortable does still work. But if *ANY* parent element uses a Bootstrap Col, iPad Safari will not sort.

Did Bootstrap introduce this issue or ng-sortable?

This is breaking the site we're currently building, which must work on iPad Safari. Please let us know if we need to take this up with Bootstrap.

    Thanks,
               JB

**Comment by a5hik** [comment]
@johnbrunnings I just had a look at Mac with safari, it works perfect.
However the case you mentioned should be a problem with the touch devices.. I'm waiting for an iPad to test.. will update you in a day.

**Comment by a5hik** [comment]
Didn't get an iPad yet, will update on this soon.

**Comment by gquintana16** [comment]
Have tried this on an iPad yet?  I am experiencing the same issue.

**Comment by a5hik** [comment]
let me close this and track via #215
