### ISSUE TITLE
Issue using control with Table rows

### ISSUE THREAD

**Issue by mattnibs** [a5hik/ng-sortable#21]
When I use this with a table there's a couple of issues:
1. The display: block for sortable-item and sortable-placeholder move all the columns in the table into the first row
2. Generally the default css is very opinionated and messes with the css I have for the table
3. It would be nice if there were some logic to detect if the drag and drop is a table then have it set the height of the dragging item dynamically to the drawn height of the original row. Additional you could loop through and dynamically set the table row width to same width of the original row.

Other than that, great angular control!

**Comment by gbittmann** [comment]
It looks like this is back? I found this in the min and had the same table problem described. It was fixed by commenting out display: block;

```
.as-sortable-placeholder {
display: block;
}
```
