### ISSUE TITLE
Element not showing when dragging

### ISSUE THREAD

**Issue by rcrodrigues** [a5hik/ng-sortable#210]
Hey folks, I'm using the ng-sortable as the documentation says. However, I can't see the element when dragging. I'm using 2 lists with a customized bootstrap timeline (Don´t want to transfer element from one list to another). I tried to change the dragging css class without success. Any Ideas what I could be missing?
 
Example:
![screenshot_6](https://cloud.githubusercontent.com/assets/5162098/9469709/f065540a-4b1e-11e5-9a51-874c47c8d165.png)

**UPDATE**: added the containerPositioning param and it started working thoroughly.

**Comment by a5hik** [comment]
@rcrodrigues thanks for the update. let me close this.
