### ISSUE TITLE
copy all items list when dragging 

### ISSUE THREAD

**Issue by R-iskey** [a5hik/ng-sortable#211]
I've html structure like this:

<code>
ul as-sortable="dragControlListeners" <br/>
  li as-sortable-item <br/>
    div as-sortable-item-handle <br/>
</code>

When I've start to drag items (li), I did see some problems with css(because on my ul I set column-count).
Then I open ng-sortable.js and replace sortableScope with itemScope on line 685 and all be fine.
This problem created from wrong tag clone, I need to clone list items, but not ul.

See code
<code>
dragElement = angular.element($document[0].createElement(scope.sortableScope.element.prop('tagName')))
              .addClass(scope.sortableScope.element.attr('class')).addClass(sortableConfig.dragClass);
</code>

replace
<code>
dragElement = angular.element($document[0].createElement(scope.itemScope.element.prop('tagName')))
                .addClass(scope.itemScope.element.attr('class')).addClass(sortableConfig.dragClass);
</code>

**Comment by a5hik** [comment]
@R-iskey this change is intentional as to have this work on touch devices. 

If you could see I only create the parent element 'ul' and size as 'li'.

            dragElement.css('width', $helper.width(scope.itemScope.element) + 'px');
            dragElement.css('height', $helper.height(scope.itemScope.element) + 'px');

and you can see I again append the 'li' element.

dragElement.append(scope.itemScope.element);

the demo pages are using the same structure you describe.

**Comment by R-iskey** [comment]
@a5hik but I've problem with css , which I add to my ul (column-count:5), you can try and see what I've mean.

![untitled](https://cloud.githubusercontent.com/assets/12074147/9497764/abc57ad2-4c27-11e5-88bb-f55ed6aea869.png)



for example set the <ul> element column-count:5 and create the sortable structure like in your demo page.

**Comment by a5hik** [comment]
can you try apply the CSS indirectly for the as sortable? something like parent div > as.sortable .  let me know if this works.

**Comment by R-iskey** [comment]
No any changes (

**Comment by a5hik** [comment]
@R-iskey actually this is the one line which is causing this issue. 

.addClass(scope.sortableScope.element.attr('class'))

 let me regress it thoroughly and remove it If needed.

**Comment by R-iskey** [comment]
yes I've replaced this class with itemScope class. think this is good solution for this problem. Thx for your replies.
