### ISSUE TITLE
Only want to know source and dest, but items should always stay the same

### ISSUE THREAD

**Issue by JosephDAM** [a5hik/ng-sortable#213]
Title quite says it all. I have a bunch of elements, in rows and columns, tried table, divs, and now I'm going to try with lists. The thing is, I want elements to always stay the same, when I'm draggin an element I don't want the others to move. And when im finished dragging, I just want to fire an event to do "merge" options, but not actually change the structure or position of the elements. Even the "merged" elements should stay in the same position. Writing this I realise that what I want is the drag utility and the triggered events, but not the sorting. I already have as-sortable in another part of the app and works perfect. Thanks in advance and gj on this module :)

**Comment by JosephDAM** [comment]
In case I didn't express myself properly. I would like to know if there is a way to disable the sort function. 
Only the item you drag, and only while you are dragging it, should be moving, all other elements should stay in place, that means when I'm dragging an item the other items should not move to make "place" for that item. The moment you let go, the item should go to its original position and the callback should catch source and dest like it does now. Is this possible?

**Comment by a5hik** [comment]
>>I would like to know if there is a way to disable the sort function
you can do this by returning the accept callback always 'false'. please see the demo samples.

**Comment by JosephDAM** [comment]
The only problem is dest gives me the same index as source. Is there a way to know where I "dropped", or tried to drop, the item I was moving? And thanks again

**Comment by a5hik** [comment]
@JosephDAM please check the doc.

In the accept callback you have an destItemScope param.
callbacks.accept = function (sourceItemHandleScope, destSortableScope, destItemScope) {}; 

from that you can get the dest item details, and always check for the 'undefined'.
