### ISSUE TITLE
Stopping propagation within the directive

### ISSUE THREAD

**Issue by gugahoi** [a5hik/ng-sortable#216]
Was wandering what is the correct way to go about stopping the propagation of the event within this directive? The use case is that there is a text input inside of the drag handle and I would like the user to be able to select the text by dragging the mouse over the text however at the moment it will initiate the dragging of the element. Any tips are greatly appreciated!

**Comment by gugahoi** [comment]
Seems like `ng-mousemove` is the way to go however it is still a little "buggy". As soon as the mouse leaves the input box, event if selecting text, the element dragging triggers.

**Comment by a5hik** [comment]
this is done via moveListen listener, hence closing this issue.
