### ISSUE TITLE
Controller 'asSortable' can't be found

### ISSUE THREAD

**Issue by yellowiscool** [a5hik/ng-sortable#225]
Hi,

We use ng-sortable with Angular 1.4.7 and Angular Material 0.11.0 (but the errors also occurred with previous versions) and we randomly get the following error:
`[$compile:ctreq] Controller 'asSortable', required by directive 'asSortableItem', can't be found!`

Except the error message, we do not see any problem. It might append when we dynamically add a new as-sortable-item but I can't reproduce the problem. I just see it sometimes.

We use it like this (and functions is an array that changes dynamically):
```html
<div as-sortable="dragControlListeners" ng-model="functions">
    <div as-sortable-item ng-repeat="funct functions" flex>
        <div as-sortable-item-handle layout="row" layout-align="center">
             <a-directive function="funct"></a-directive>
        </div>
    </div>
</div>
```

**Comment by CClerville** [comment]
@yellowiscool could this be because your `ng-repeat` is incorrect. I think you meant to do this:
 `funct in functions`.

**Comment by yellowiscool** [comment]
Sorry, it's a typo when I copied and simplified it in this issue. I don't think it works at all without the `in` keyword.

**Comment by MarkOdey** [comment]
I am having this similar problem

Controller 'asSortable', required by directive 'asSortableItem', can't be found!


<ul class="list-file cf text-white" data-as-sortable="dragListeners" data-ng-model="data.products">		
		<li ng-repeat="product in data.products data-as-sortable-item>
			<div  data-as-sortable-item-handle class="col-6 col pad-t_sm truncate">                   
                             {{product.title}}</div>
			</div>
                </li>
	</ul>

**Comment by peio72** [comment]
+1

**Comment by peio72** [comment]
Any update possible to solve this issue ? Thanx.
