### ISSUE TITLE
Doesn't work with tables

### ISSUE THREAD

**Issue by guilhermecvm** [a5hik/ng-sortable#226]
Is there any plans on making this plugin working with tables?

**Comment by a5hik** [comment]
@guilhermecvm the sprint example on the demo uses table structure.

**Comment by MaitreDede** [comment]
The sprint example repeats a <td> inside a table.
Does it work for table rows ?
It seams that it is kinda ugly : http://plnkr.co/edit/eZepNR1OomLBHaDa2Rfj?p=preview

**Comment by guilhermecvmnsj** [comment]
@a5hik as @MaitreDede said, it does not work with table rows..

**Comment by markantill** [comment]
This is now the third drag an drop library for angular I have rejected for my project for not supporting tables. Such a shame it was good in every other respect. I think it is the block formatting causing the issue meaning the row content doesn't align with the headers, but changing it to table-row make a mess when dragging it around.

**Comment by a5hik** [comment]
@guilhermecvm @M4v3R @markantill please check with the latest as this is fixed as part of #237

**Comment by johannesjo** [comment]
The support is still very wonky also with the latest release. It's still like @markantill describes it, the formatting is messed up because of display: table-row is overwritten or if you change that, it is when dragging a row.
