### ISSUE TITLE
track by not work

### ISSUE THREAD

**Issue by R-iskey** [a5hik/ng-sortable#231]
problem with sorting items, when I sort items in list, after move next item cloned  2 time , for rexample I've  list
```
<ul class='list-unstyled' as-sortable='dragControlListeners' ng-model='list.data'>
     <li as-sortable-item ng-repeat='favorite in favoritesList.data  | orderBy: favorite.order | filter: filterBy track by $index' class='sortable-item animated'>[[item]]</li>
```
when I move one item this replaced with next element.
![untitled](https://cloud.githubusercontent.com/assets/12074147/10395080/17a7fe72-6eac-11e5-92c8-11eb88c69bf5.png)

**Comment by KammererTob** [comment]
I had the same problem. Here is my solution:

I added another option called `allowDuplicates` and added checks for this options at two different places:

1. At line 305
```javascript
if(this.parent.options.allowDuplicates || this.parent.modelValue.indexOf(this.source.modelValue) < 0) {
    this.parent.insertItem(this.index, this.source.modelValue);
}
```

2. At line 371
```javascript
if (typeof($scope.options.allowDuplicates) !== undefined && $scope.options.allowDuplicates) {
    $scope.modelValue.splice(index, 0, angular.copy(itemData));
} else {
    $scope.modelValue.splice(index, 0, itemData);
}
```

Now you can use duplicates without specifying  `track by $index`

**Comment by brianfeister** [comment]
+1, @a5hik can we fix this.  I found this solution to be optimal:

https://github.com/a5hik/ng-sortable/issues/128

**Comment by a5hik** [comment]
@brianfeister the allowDuplicates is added in to the master and the demo page is updated with the sample.
