### ISSUE TITLE
When ng-repeat filtered results to only 1 item, the drag drop did not pick the correct record but the first in list

### ISSUE THREAD

**Issue by ahmadalibaloch** [a5hik/ng-sortable#232]
Search by Outward Code: <input type="text" ng-model="search.Name">
    Search1 by Outward Code: <input type="text" ng-model="search1.Name">
    <div id="sortable-container"><div class="sortable-row" as-sortable="sortableOptions" ng-model="outWardCodes" style="padding:30px;margin:10px;border:1px solid red;">
        <div ng-repeat="item in outWardCodes | filter:search | limitTo:5" as-sortable-item>
            <div as-sortable-item-handle>{{item.Name}}</div>
        </div>
    </div>
    <hr />
    <div class="sortable-row" as-sortable="sortableOptions" ng-model="outWardCodes1" style="padding:30px;margin:10px;border:1px solid red;">
        <div ng-repeat="item in outWardCodes1 | filter:search1 | limitTo:15" as-sortable-item>
            <div as-sortable-item-handle>{{item.Name}}</div>
        </div>
    </div>
</div>

Now when I filter the results and only one item is in list and its like at the index of 12 then visible it will drag and drop that 12th item but after I leave the mouse the first in list at index one is actual replaced to the target and not the 12th.

Some time it gives strange results with ng-repeat filter.

**Comment by derekwzheng** [comment]
I encounter the same bug.
It seems like the ng-sortable does not work well with filter.

**Comment by a5hik** [comment]
the filters will not work with sortables, if you have to perform logics you need to do it in the callbacks provided by this plugin.

**Comment by carltu** [comment]
i used the solution provided by derekwzheng. it worked!  thanks a lot
