### ISSUE TITLE
Items on list not sorting when clone option is true

### ISSUE THREAD

**Issue by tbthiago** [a5hik/ng-sortable#236]
Hello,
This is an excellent plugin and is helping me a lot. I need the clone option, but when it's set to true, the item inside the list doesn't change order each other anymore.

**Comment by a5hik** [comment]
@tbthiago shouldn't the clone option expected to give you the copies? If it is sorting by itself the how do u perform clone?

**Comment by tbthiago** [comment]
@a5hik Sorry for not explain correctly. When clone option is set to true, I clone it in other list, but this item doesn't change the order inside the list when you drag and drop it in other position. The item remains in same position. Is that clear?
Other problem is when I use filter, the filtered item after drag and drop in other list is not correct. I changed the code passing the element as parameter instead of index. It's better, but didn't solve the problem if I do it few times.

**Comment by a5hik** [comment]
the two are not supported by this plugin.
