### ISSUE TITLE
Does not work with Directives

### ISSUE THREAD

**Issue by sszdh** [a5hik/ng-sortable#238]
Hi,
I'm coming here from `ng-ui-sortable`, so unfortunately advance using of both component is impossible!

This code does not work

```javascript
app.directive('myDirective', ['$compile', myDirective]);

function myDirective($compile) {
  return {
      restrict: 'EA',
      replace: true,
      //template: function() { return '<div data-as-sortable-item><div data-as-sortable-item-handle ' + 'sohei' + ' ng-bind="item.name" item="item"></div></div>'},
      scope: {
          type: "@",
          item: "="
      },
      link: link
  };

  function link(scope, element, attrs) {
      var view = $compile('<div data-as-sortable-item><div data-as-sortable-item-handle ng-bind="item.name"></div></div>')(scope);
      element.replaceWith(view);
  }
}
``` 

```html
<div data-as-sortable data-ng-model="items">
    <my-directive item="item" type="item.type" ng-repeat="item in items"></my-directive>
</div>
```

Error:
```console
Error: [$compile:ctreq] Controller 'asSortable', required by directive 'asSortableItem', can't be found!
```

PS. In directive inside of another directive, issue gets too complicated!

Cheers.

**Comment by a5hik** [comment]
@sszdh you need to have as-sortable element as a parent of as-sortable-item. plz refer the docs.

**Comment by sszdh** [comment]
@a5hik , This is what the directive does. Take a look at `link` function of directive. the output of directive is what it should be, but `ng-sortable` does not works!

P.S. Using `template` property instead of `link` function, generates items but with this error:

```
TypeError: Cannot read property 'dragStart' of undefined
    at http://localhost/angular-tests/lib/ng-sortable/dist/ng-sortable.js:746:30
```

**Comment by a5hik** [comment]
@sszdh can you try with the latest copy from the master. it having a fix for directive with isolated scopes.
also let me know how abt adding ur isolated directive as attribute.

**Comment by sszdh** [comment]
I'll try asap. Thanks

**Comment by jukben** [comment]
+1
