### ISSUE TITLE
Does ng-sortable deal with isolate scope?

### ISSUE THREAD

**Issue by adramalech** [a5hik/ng-sortable#240]
Hey so I have an issue with what I think is an isolate scope issue.  I have a unordered list inside of a ui-bootstrap accordion.  I try to drag something horizontally from 'Available Columns' to Custom Template.  It gives me a weird error about:

> Uncaught TypeError: this.parent.modelValue.indexOf is not a function
      apply @ ng-sortable.js:306drag
      End @ ng-sortable.js:983n.event.dispatch 
      @ jquery-2.1.4.min.js:3r.handle 
      @ jquery-2.1.4.min.js:3

I think it has something to do with the scoping, but I am not completely sure.  This is happening with ui-bootstrap-0.14.3-tpls, jquery 2.1.4, angular.js 1.4.7, and ng-sortable most current as of 11-10-2015.

This, by the way, only happens when i have things in both tableItems and columns.  If I have only tableItems (left un-ordered list) or columns (right un-ordered list) it doesn't do anything.  No error.  No moving of the card.  It acts like it is completely ignored.

Any help would be greatly appreciated.

```javascript
<div class="row">
    <div class="col-md-6 col-lg-offset-2 col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-title">Available Columns</div>
            </div>
            <div class="panel-body">
                <uib-accordion close-others="false">
                    <uib-accordion-group ng-repeat="table in $storage.tables">
                        <uib-accordion-heading>
                            {{table}} <i class="pull-right" ng-class="{'fa fa-chevron-down': collapsed[table], 'fa fa-chevron-left': !collapsed[table]}" ng-click="collapsed[table] = !collapsed[table]"></i>
                        </uib-accordion-heading>
                        <ul as-sortable ng-model="$storage.columns[table]">
                            <li ng-repeat="item in $storage.columns[table]" as-sortable-item no-drag>
                                <div class="card" as-sortable-item-handle>
                                    <div class="card-content">
                                        <p class="pull-right mr5">{{item.table}}</p>
                                        <p>{{item.column}}</p>
                                    </div>
                                </div>
                            </li>
                        </ul> 
                    </uib-accordion-group>
                </uib-accordion>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-title">Custom Template</div>
            </div>
            <div class="panel-body">
                <ul as-sortable ng-model="$storage.tableItems">
                    <li ng-repeat="item in $storage.tableItems track by $index" as-sortable-item>
                        <div class="card" as-sortable-item-handle>
                            <div class="card-content">
                                <p class="pull-right mr5">{{item.table}}</p>
                                <p>{{item.column}}</p>
                            </div>
                            <div class="card-action">
                                <a class="pull-right btn btn-sm" ng-click="removeCard($index)">Remove <i class="fa fa-times"></i></a>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
```

**Comment by a5hik** [comment]
>>If I have only tableItems (left un-ordered list) or columns (right un-ordered list) it doesn't do anything. No error. No moving of the card. It acts like it is completely ignored.

Hi I see a 'no-drag' attribute set on 'sortable-item' so you wont get the drag working.

**Comment by adramalech** [comment]
Yea so I remove that attribute and still see a problem.

When I drag from one column to the other column I get an error:
ng-sortable.js:983  dragItemInfo.apply();  
ng-sortable.js:306
```javascript
      if(this.parent.modelValue.indexOf(this.source.modelValue) < 0) {
            this.parent.insertItem(this.index, this.source.modelValue);
      }
```

this.parent.modelValue points to an object, not an array/list.  Erroring on indexOf.  Is there something I am missing in the above HTML?  Like do I need a special ng-model value to make this work?  I am going to try it without the ui-bootstrap accordions and see if it changes how it behaves.

Thanks for the reply and help!

**Comment by adramalech** [comment]
Okay so I figured out the model at the scope of as-sortable needs to be a list.  I was being dumb and referencing a model that held the list not the list itself fixing that fixed the issue.
