### ISSUE TITLE
Swap index instead of displacing

### ISSUE THREAD

**Issue by Sheepzez** [a5hik/ng-sortable#242]
I have a list of 9 items that are displayed as 3 columns of 3. 

When I drag an item from the center location (position  4) to top left (position 0) I would like the item currently in position 0 to swap with the dragged item (back to position 4).

What is the best way to do this?

I tried searching, but came up short, and I'm not fluent enough with Angular in general to figure it out.

Thanks!

**Comment by a5hik** [comment]
@Sheepzez right now you can't do this with this plugin as this is designed to perform sortable. however this is possible with some modifications with the plugin code.

**Comment by Sheepzez** [comment]
I ended up using [Angular Gridster](https://github.com/ManifestWebDesign/angular-gridster/) for the type of grid functionality I wanted.
