### ISSUE TITLE
Determine order of entire list?

### ISSUE THREAD

**Issue by jhendley25** [a5hik/ng-sortable#246]
I'm working on a draggable list of questions, and I'd like to be able to retrieve the index for each item at once (after one item is moved for example). Is there a way to do this? I apologize if I'm just missing something.

Great library by the way.

**Comment by a5hik** [comment]
@jhendley25 you just need to see the demo samples. and there are callbacks exposed and that will have the model exposed.

**Comment by jhendley25** [comment]
@a5hik Can you point me to the relevant callback? The only callback I see that looks helpful is orderChanged, but it only gives me information about the individual item that was moved. I'd like to be able to see the current position of all items in the list after the list order is changed. Is this possible?

**Comment by a5hik** [comment]
@jhendley25 you can access it via event.dest.sortableScope

**Comment by a5hik** [comment]
just see - https://github.com/a5hik/ng-sortable#parameters-1 this part of doc.

**Comment by jhendley25** [comment]
Fantastic, thanks for the help!
