### ISSUE TITLE
Wrong position of item when dragging (using table tab on demo)

### ISSUE THREAD

**Issue by dani3l** [a5hik/ng-sortable#250]
Hi, just installed from master and when going to table tab on demo that item position when dragging is wrong.
![bug](http://4il.net/sortbug.gif)

This also happened to me when I tried to use it last week.
Any idea what causes that and how to fix?

BTW - ui sortable (with jquery ui) has a huge memory leaks going on so thank you for this plugin! this one actually saved me a lot of headache

**Comment by SakshiParakh** [comment]
this is similar to the issue  #174. I have mentioned the solution there.

**Comment by dani3l** [comment]
Worked like a charm! thanks :)
