### ISSUE TITLE
Relative containment, is it possible?

### ISSUE THREAD

**Issue by Darksoulsong** [a5hik/ng-sortable#255]
Is it possible to set a relative `containment` option instead of an ID? I have nested `as-sortable` directives where the nested items aren't supposed to be drag outside its parent div. I'm looking for something like so:

    nestedSortableOptions = {
        containment: angular.element(this).parents('.nestedItemContainer')
    }

**Comment by a5hik** [comment]
@Darksoulsong the containment option is a defined one and static.
