### ISSUE TITLE
Is there a way to detect an item is dropped outside of its original scope?

### ISSUE THREAD

**Issue by excentris** [a5hik/ng-sortable#256]
I would like to detect when an item is dropped outside of its original scope in order to remove the item. Is there a way to accomplish this?

**Comment by a5hik** [comment]
@excentris not sure what do u mean by outside of the scope but there are callbacks provided which you can use it to implement custom logics.

**Comment by excentris** [comment]
Sorry I wasn't clear. I have one div `as-sortable` with different `as-sortable-item` items inside it. I would like to detect when one of those items is dragged and dropped outside of the `as-sortable`. I have tried to use `dragEnd` but I can only detect if the `dest` becomes a different `as-sortable`, because when dropping somewhere else on the page the `as-sortable-item` returns to the original `as-sortable`.

Essentially what I am trying to accomplish is making the whole space around the `as-sortable` some kind of drop-zone to remove the items...

**Comment by a5hik** [comment]
The directive is designed to be dropped only at any as-sortable so u have to define the drop zone as another as-sortable.

**Comment by excentris** [comment]
Ok. Thanks. That is indeed what I ended up doing, although I think it could be handy to have a callback to be able to implement what I was trying to accomplish.
