### ISSUE TITLE
<TR> dragging removes CSS styling 

### ISSUE THREAD

**Issue by nathansokol** [a5hik/ng-sortable#264]
Hi Ashik, 

Awesome plugin. Just started using this one. I have a minor issue that I am running into.

Here is my HTML (plus bootstrap's "table" element)

    <tbody data-as-sortable="dragControlListeners" ng-model="team.players">
        <tr ng-repeat="player in team.players" id="player-row-{{player.id}}" data-as-sortable-item>
            <td data-as-sortable-item-handle style="width: 1em;color: #BBB;">...</td>
            ....
            <td>{{player.name}}</td>
            <td>{{player.location}}</td>

The drag and drop effect is working awesomely, but the CSS styling of the dragged element is appearing to not keep the same CSS pre-drag. It appears to set the elements to "display:block" and remove the background-color, or set it to "transparent".

![ng-sortableissue](https://cloud.githubusercontent.com/assets/1711372/12224590/62f26288-b7b2-11e5-9e98-14037c27ebcb.jpg)

Hopefully you can see what I mean about the element being dragged and the CSS being removed. I tried to use a red arrow to point to the issue.

Here is the CSS class I tried from the docs to apply to keep the "table-row" effect with no success (however, putting in a border/bg on the .as-sortable-dragging class did work properly; just not the table-row display property.):

    .as-sortable-dragging {
        display: table-row !important;
    }

**Comment by nathansokol** [comment]
If anyone else is having this issue, I solved it by applying these classes.

    .as-sortable-dragging {
        display: table !important;
        border-collapse: collapse; /* bootstrap table styling */
    }

    .as-sortable-dragging td {
        display: table-cell !important;
        border: 1px solid #DDD; 
        padding: 8px; /* bootstrap table styling */
        line-height: 1.42857143; /* bootstrap table styling */
        vertical-align: top; /* bootstrap table styling */
}

**Comment by Aakash447** [comment]
Hello I am using HTML,CSS table, and using react-beautiful-dnd to drag it.
it works fine ,but same problem , on dragging it is losing its styling, what to do in this case.
