### ISSUE TITLE
[Issue] Cant make allowDuplicates to work

### ISSUE THREAD

**Issue by AmitMY** [a5hik/ng-sortable#272]
I have two ng-sortable blocks, when one is set to "clone", and I want the other to b set to disallow duplicates.
I used (tried on both): allowDuplicates: false, and then even allowDuplicates: true.
This does not seem to work, and I can drag several instances of the same to the block.

I thought it was me using objects in my array: [{a: 1, label: "1"}, {a: 2, label: "2"}], so I changed it to just a string array: ["1","2"], and it did not work.

What do I need to do to disallow duplicates?

**Comment by a5hik** [comment]
@AmitMY you just not to put any token of 'allowDuplicates' that will do good.

**Comment by garymazz** [comment]
I have also tried and have removed allowDuplicates. Duplicates are still permitted.

**Comment by hkong** [comment]
I also could not get ``allowDuplicates`` to work (version 1.3.2).  I ended up doing this, but it involves modifying nsSortable slightly:

In ``ng-sortable.js``, at line 390, modify ``$scope.insertItem`` to
```
$scope.insertItem = function (index, itemData) {
      var isNew = !$scope.options.isDuplicate( itemData, $scope.modelValue );
      if ($scope.options.allowDuplicates || isNew ) {
        $scope.modelValue.splice(index, 0, angular.copy(itemData));
      }
    };
```
then in your controller code, add this to the options definition:
```
$scope.options = {
...
isDuplicate: function( item, listToCheckAgainst ) {   
    var index = listToCheckAgainst.findIndex(function(currentValue) {
    return currentValue.Label === item.Label;
    });
    return ( index >= 0 ) ? true : false;
},
allowDuplicates: true,
...
}; 
```
