### ISSUE TITLE
Can i make item draggable & clickable at the same time ?

### ISSUE THREAD

**Issue by MayankLogiciel** [a5hik/ng-sortable#273]

**Comment by a5hik** [comment]
@MayankLogiciel you can make a 'clickable' element inside a 'draggable' element.

**Comment by MayankLogiciel** [comment]
@a5hik  Below is the html structure for my drag drop behaviour.. I want to drag/drop images(having as-sortable-item-handle) into some other container also want click on them to show image bigger preview.

I have added ng-click="sayHello()" on img tag having "as-sortable-item-handle".

Whenever sortable behaviour is disabled , ng-click="sayHello()" works. As soon as i enable sortable behaviour ng-click="sayHello()" doesn't work.

Do you have any idea about it. What is wrong with my html structure?

```
    <ul class="list-unstyled list-inline"
        id="drag-sortable-container"
        as-sortable="dragableCloneOptions"
        is-disabled="!isSlideDragDropEnabled"
        ng-model="presentationSlides">
        <!--loop bof-->
        <li class="" ng-repeat="slide in presentationSlides" >
            <ul class="list-unstyled">
                <li class="chkboxli">
                <input 
                    type="checkbox" 
                    id="slide@{{$index}}"
                    ng-model="slide.isSelected"
                    ng-change="applyFilterFor('select_unselect_slide', slide)"
                    ng-true-value="true"
                    ng-false-value="false"
                    name="slide@{{$index}}" />
                    <label for="slide@{{$index}}"></label>          
                </li>
                <li class="imgbox">
                    <img
                        ng-click="sayHello()"
                        as-sortable-item 
                        as-sortable-item-handle
                        id="slide-image-@{{slide.id}}"
                        width="154"
                        ng-src="@{{getImageUrl(slide.id, 'thumbnail')}}">
                    <img src="/images/greenAdd.png" class="slideAdd" ng-click="open()">
                </li>
                <li class="nameli">
                    <a href="#" ng-bind="slide.title"></a>
                </li>
            </ul>
        </li>
        <!--loop eof-->
    </ul>
```

**Comment by MayankLogiciel** [comment]
Oops! My bad.. The click issue is generated due to the changes i have done in plugin's js file by referencing this [issue](https://github.com/a5hik/ng-sortable/issues/61) as he suggested to take the dragStart(event); out of thevar moveListen = function ... function and it all seems to work in FF now. This is around line 593 in the ng-sortable.js file.

When i reverted these changes click event is working fine for me.. But now my drag drop has issues on firefox browser as explained in [close issue](https://github.com/a5hik/ng-sortable/issues/61).

Please guide me the right way to resolve the issue whether it is problem with my css or html structure or anything else.
