### ISSUE TITLE
[Contribution] Fix placeholder CSS display

### ISSUE THREAD

**Issue by AmitMY** [a5hik/ng-sortable#274]
In two places there is a code: "// Ensure the placeholder is visible in the target (unless it's a table row)"
Which does
`if (placeHolder.css('display') !== 'table-row') {
              placeHolder.css('display','block');
            }`

Now, display block will override any custom css given to the draggable item (for me, it is inline-block), so instead you should user:

`if (placeHolder.css('display') !== 'table-row') {
              placeHolder.css('display', $("."+sortableConfig.itemClass).css('display'));
            }`

This will ensure it will display correctly.

If this is implemented, or there is a problem implementing it, please let me know.

**Comment by benjaminapetersen** [comment]
Quick comment, this repo doesn't rely on jQuery, so you don't have acess to `$` or `.css`.  You could check out docs for Angular's `element` (jQlite) and provide a pure angular fix.
https://docs.angularjs.org/api/ng/function/angular.element

**Comment by benjaminapetersen** [comment]
Prob could title the issue better as well.

**Comment by AmitMY** [comment]
Well, in the distribution file, you do use `.css`, alot.
https://github.com/a5hik/ng-sortable/blob/master/dist/ng-sortable.js

I probably could have, but it is a bodge... and I have no idea what would be a fitting issue :)

Here is a different fix, using plain JS: (not even needing angular)
`document.querySelector("."+sortableConfig.itemClass).css('display'));`
Using JS built in selector, not jQuery's

**Comment by benjaminapetersen** [comment]
Could be titled "Fix placeholder CSS display".  Is definitely more meaningful :)

**Comment by LouTerrailloune** [comment]
The JS code that set the display property should be removed and the positioning should be set by CSS.

You can also override the positioning via CSS:
```
.as-sortable-placeholder {
  display: inline-block !important;
}
```
