### ISSUE TITLE
[Feature] Scrolling on Touch devices

### ISSUE THREAD

**Issue by maveric1977** [a5hik/ng-sortable#275]
As you know, dragging is natively used by touch devices for scrolling. Using the ng-sortable on a touch screen, one can not scroll in a list anymore as dragging will be used to re-order the elements.
My proposal would be to enable the ng-sortable drag only after "touch and hold" i.e. `oncontextmenu` event when running on a touch screen device (`'ontouchstart' in $window`).
Would such a feature be of interest by others as well? If so I can prepare a pull request addressing this feature.

**Comment by a5hik** [comment]
@maveric1977 yes this seems to be good option, but this needs to be controlled and optional by a param.

**Comment by maveric1977** [comment]
@a5hik as proposed, there is now a `longTouch` option in the sortable `sortOptions`.
