### ISSUE TITLE
Input elements in sortable container

### ISSUE THREAD

**Issue by digitalw** [a5hik/ng-sortable#280]
I am havin gissues with <input> within a <md-card data-as-sortable-item-handle>...
I can not enter any values in to these elements. Adding click event however works. Also changing the value from the controller also works. 
Tried it with <input type="number"> and  <input type="text">. Weired thing is that i am able to select values from a <md-select> 

Is thera general issue with this or should this work.

thanks for the help

**Comment by digitalw** [comment]
I created a Plunker illustrating the issue. 
http://plnkr.co/edit/pNJD26eJdkuuzJVA0ys8

**Comment by derlin** [comment]
I have the same problem with a `select` inside a draggable. The drop-down is not showing. Any idea how to fix it ?

**Comment by derlin** [comment]
Found a solution !

The elements marked as `data-as-sortable-item-handle` will override the on-click events, so inputs won't work. Fix: use a title or an icon for the handle, so the input is not a child of it !

**Comment by a5hik** [comment]
You can use no-drag for input elements/ click events inside as-sortable-item-handle.
