### ISSUE TITLE
Mouse click not detected, but touch screen touch is

### ISSUE THREAD

**Issue by timothylippiatt** [a5hik/ng-sortable#281]
When attempting to sort items, mouse click drags do not seem to be detected when using Chrome, but touch screen drags are. Have tested without extensions and in incognito mode. Chrome Version 48.0.2564.109 m

Have also tested on MS Edge and both touch and mouse click sorting works fine.

**Comment by a5hik** [comment]
@timothylippiatt this a sort of first time im hearing .. didi u tried accessing the demo page?

**Comment by astynax777** [comment]
The issue I found was when the you click in the box and not on the text.  You must click on the text to drag.

**Comment by rghv28** [comment]
It happens only in Chrome for me as well, problem is when you have click event like "X" (close card)in http://a5hik.github.io/ng-sortable/#/sprint
the event is not fired sometimes in chrome. Firefox and IE are fine.

**Comment by rghv28** [comment]
This happens only on touch screens
ipad/safari
chrome

**Comment by knchess** [comment]
This is affecting me since commit 453988fbe7a86d0570bbb5e4f755e591da6560bc
When I disable touchscreen and restart browser, mouse dragging works again (I'm using Chrome 49)

**Comment by a5hik** [comment]
@maveric1977 can you have a look in to this.. #275

**Comment by maveric1977** [comment]
@a5hik I'll check it out tonight

**Comment by timothylippiatt** [comment]
@a5hik I can confirm that both the simple and advanced demo pages do not drag with my mouse click in Chrome (49.0.2623.87 m), only touchscreen dragging works.

I tested the same pages in MS Edge and both work with mouse and touch.

**Comment by maveric1977** [comment]
@a5hik , @timothylippiatt : Just checked the [demo page](http://a5hik.github.io/ng-sortable) using the latest version of Google Chrome (49.0.2623.87 m) and everything works fine. I cannot reproduce the problem.

**Comment by BenArunski** [comment]
I can confirm this issue in Chrome, when using a mouse on a touch-screen laptop.
