### ISSUE TITLE
Not working on laptop with touch screen on Chrome latest version.

### ISSUE THREAD

**Issue by mihaic-gf** [a5hik/ng-sortable#285]
[demo.zip](https://github.com/a5hik/ng-sortable/files/158690/demo.zip)

Hello,

This is the best touch library for angular that I've seen.
I have only one small problem that puzzles me.

On a laptop with touch enable screen, in Chrome, it doesn't work. (If you don't have this kind of laptop you can simulate it by going to about:flags and setting "Enable touch events" to Enable)

Now the puzzle: if I open the demo from github directly it works, if I open the demo from localhost it doesn't work anymore.(see attached file with localhost demo)

Any help is greatly appreciated.

Thanks,
Mihai

**Comment by a5hik** [comment]
@mihaic-gf the demo is not updated for a while.. so I guess something might have broken with latest commits.

**Comment by mihaic-gf** [comment]
@a5hik I see that the demo loads version 1.3.2 of the ng-sortable, the same that i'm using on localhost.

I got to this example because it doesn't work on the touch laptop in my implementation using 1.3.2.
The only way to make it work on the touch laptop was to enable "longTouch" and then you can right click to start drag, but this is not very intuitive for the user.

**Comment by a5hik** [comment]
@mihaic-gf can you please try with the master version of the library.
and providing some error log would help me to narrow down the issue. 
and moreover not everyone having the touch screen laptops to test it ;-)

**Comment by mihaic-gf** [comment]
@a5hik I have build the dist files from the master version and it still doesn't work

There is no error message, clicking on the draggable items doesn't trigger the dragStart event.

If you don't have a touch laptop you can simulate it by going in Chrome to "about:flags" and setting "Enable touch events" to Enable

**Comment by mihaic-gf** [comment]
BTW did you updated the demo on the githhub? because that doesn't work anymore.
