### ISSUE TITLE
longTouch option watcher always fires bindDrag

### ISSUE THREAD

**Issue by skoszuta** [a5hik/ng-sortable#287]
Hello everyone,

Here's a link to the code I'm talking about in the issue title:
https://github.com/a5hik/ng-sortable/commit/453988fbe7a86d0570bbb5e4f755e591da6560bc#diff-20d50cfbb7bfa390a7080aea43fb3aa5R656

Since 1.3.3 this code seems to make my elements draggable even though is-disabled is set to true. Please correct me if I'm missing something here.

Thanks
Sebastian

**Comment by millerf** [comment]
I noticed the same thing...

**Comment by a5hik** [comment]
this is fixed with the master branch.

**Comment by skoszuta** [comment]
neat, thanks!
