### ISSUE TITLE
Cannot drag-and-drop in IE 11 and IE 10

### ISSUE THREAD

**Issue by AshokR** [a5hik/ng-sortable#288]
When I hover over the list item I see the drag cursor, but I cannot drag-and-drop. I see the following error in the developer tools console:
SCRIPT16389: Unspecified error.
File: ng-sortable.js, Line: 85, Column: 11

**Comment by a5hik** [comment]
@AshokR actually the demo page was bit outdated. so you were seeing those errors. 
But never mind the demo is updated now. so u should not see this issue anymore.
