### ISSUE TITLE
Incorrect insertion when using track by

### ISSUE THREAD

**Issue by beesden** [a5hik/ng-sortable#299]
If a ng-repeat list is using track by, when the list is sorted the wrong child is being copied (the original is still being removed) and so when that element is resorted it is removed as it already exists in the list.

```
<tbody data-as-sortable data-ng-model="myList">
    <tr data-ng-repeat="item in myList track by $index" data-as-sortable-item>
        <td data-as-sortable-item-handle data-icon="drag"></td>
        <td>{{ item.name }}</td>
        <td>
            <button type="button" data-ng-click="doSomething( $index )">Click me!</button>
        </td>
    </tr>
</tbody>
```

**Comment by stevehanson** [comment]
I am seeing this too. This at least pointed me to the fact that `track by` was causing my issue.

**Comment by vncnz** [comment]
Same problem :-/

**Comment by valuka** [comment]
I can confirm the same issue.

**Comment by raduburcuta** [comment]
I have the same problem.

**Comment by cbier** [comment]
See https://github.com/a5hik/ng-sortable/issues/221. I believe these are related

**Comment by a5hik** [comment]
the trackby will not work properly with ng-sortable. and this is documented.
