### ISSUE TITLE
Clone feature

### ISSUE THREAD

**Issue by maxiruani** [a5hik/ng-sortable#3]
It wourld be nice to be able of cloning the items.

If you disable the sorting with accepts, and you can clone the items, you transform the list in a draggable one very quickly.

**Comment by juusopimia** [comment]
+1 Have used the copy-workaround mentioned above, but the dragged item still disappears from the original zone when it's dragged on top of another zone. Any hints to prevent this?

**Comment by etcook** [comment]
+1

**Comment by dolphub** [comment]
+1 I would also love to have the cloning option.  Otherwise great work!

**Comment by karthickannan** [comment]
Along with the solution provided here (https://github.com/MrMDavidson/ng-sortable/commit/cdfd6dc3eed3916638b86012e9a266b167b0d7b4), I have edited the ng-sortable.js for cloning the elements. I don't see any issues. Please let me know if you guys face anything.

I have replaced the apply function of dragItem (Line no: 293) with the below code:

```javascript
apply: function () {

    // If clone is not set, set it to false
    if (typeof (this.sourceInfo.sortableScope.options.clone) === 'undefined') {
        this.sourceInfo.sortableScope.options.clone = false;
    }

    // If clone is not set to true, remove the item from the source model.
    if (this.sourceInfo.sortableScope.options.clone == false) {
        this.sourceInfo.sortableScope.removeItem(this.sourceInfo.index);
    }
    
    // If the dragged item is not already there, insert the item. This avoids ng-repeat dupes error
    if(this.parent.modelValue.indexOf(this.source.modelValue) < 0) {
        this.parent.insertItem(this.index, this.source.modelValue);
    }
    
}
```

**Comment by sbaglieri** [comment]
excelente work karthickannan !

**Comment by karthickannan** [comment]
Thank you @sbaglieri 

Please let me know if you face any issues after changing the code

**Comment by amcdnl** [comment]
Documentation would be nice for this.

**Comment by amcdnl** [comment]
@a5hik is there a plan to merge this soon?

**Comment by a5hik** [comment]
@amcdnl will do is soon after some testing, I was busy for a while.

**Comment by chaddjohnson** [comment]
Thank you for the patch, AxxlForce. I tried this out, and I'm noticing when I drag an element from a source list, the item is still removed, and it's added back when I drop the item in the target list. So in reality it's not actually cloning.

Your patch does this: http://jsfiddle.net/v265q/
In my opinion, it would be better for it to work like this: http://jsfiddle.net/vaibviad/njYqA/214/

**Comment by chaddjohnson** [comment]
@a5hik and everyone, I've provided an alternative solution for the `clone` option. Just provide `clone: true` as an option, and this should work. This solution prevents items from being removed from the source list at all. Documentation will need to be updated.

I've created a pull request.

**Comment by a5hik** [comment]
@chaddjohnson did u get a chance to look at the pull request for #175 also It would be good If you demonstrate the changes with a plunker along with readme changes?

**Comment by chaddjohnson** [comment]
Crap, didn't realize that existed. I'll have to look at that soon.

**Comment by karthickannan** [comment]
@a5hik  Have you merged my code with your code??

@chaddjohnson Is this code working fine or is there any issues ??

**Comment by chaddjohnson** [comment]
My code seems to work fine without issues.

I have not had time to look at the other code or test it.

**Comment by a5hik** [comment]
@wonskarol yes will be doing it. in max 2 days. extremely busy with other things. will update you.

**Comment by wonskarol** [comment]
Thank you @a5hik

**Comment by wonskarol** [comment]
There's one more thing ... as @juusopimia noticed (https://github.com/a5hik/ng-sortable/issues/3#issuecomment-69013948), the dragged element at first disappears from source container and when dropped in destination container, appears again. I mean, this same happens in @karthickannan solution. Is it possible to prevent this behavior?

**Comment by a5hik** [comment]
@wonskarol sure will check this as well.

**Comment by karthickannan** [comment]
@wonskarol Thank you for pointing out that issue. I'll work on this and provide the solution within the end of this week.

**Comment by a5hik** [comment]
@wonskarol and all I had tested the patch #204 from @chaddjohnson and @karthickannan and it works fine and merged the same, please take the latest from the master, and let me know If you see any issues.

- Ashik

**Comment by wonskarol** [comment]
Hi @a5hik,

great job! I don't see any issues, everything works fine :)

**Comment by a5hik** [comment]
Ok Great, let me close this issue.

**Comment by chaddjohnson** [comment]
Awesome!

**Comment by amcdnl** [comment]
Any docs?

**Comment by wonskarol** [comment]
Is already on main page: 
```
$scope.dragControlListeners = {
    accept: function (sourceItemHandleScope, destSortableScope) {return boolean}//override to determine drag is allowed or not. default is true.
    itemMoved: function (event) {//Do what you want},
    orderChanged: function(event) {//Do what you want},
    containment: '#board'//optional param.
    clone: true //optional param for clone feature.
};
```
@a5hik: are you going to tag a new version 1.3.1?

**Comment by a5hik** [comment]
Yeah, I will be tagging a new version soon.

**Comment by tbthiago** [comment]
With clone option set to true, the list is not sortable anymore.
Anybody got this problem? How to solve?

**Comment by torreant** [comment]
hi @tbthiago, i'm facing the same issue: "with clone set to true, the list is not sortable anymore".
Did you find a solution to solve it?
Thanks
