### ISSUE TITLE
Input fields no longer gain focus

### ISSUE THREAD

**Issue by loganom** [a5hik/ng-sortable#304]
It seems that commit 5e7b2e1ef6deb09db46e27b61004456c46f34f76 prevents some click events since 1.3.3.

We noticed this when we upgraded from 1.3.2 and were no longer able to have input fields within our sortable elements (they will never gain focus). Removing the `event.preventDefault` added by this commit solves our issue, but we are hesitant without understanding why it was added to begin with. Perhaps @maveric1977 or @a5hik could add some insight into this? (aside from the commit message, of course)

I believe that this may possibly be related to a separate issue (https://github.com/a5hik/ng-sortable/issues/302). 

A rough example can be found here: [plunkr](https://plnkr.co/edit/lNKDNymBOqXbA9yoh55p)

**Comment by cbier** [comment]
+1 I am experiencing the same issue

**Comment by a5hik** [comment]
@loganom thanks for pointing this out. made the required changes in master. let me also release a new version for this Fix.

**Comment by cbier** [comment]
@a5hik Thank you so much for this update and the quick response :) It works great now

**Comment by loganom** [comment]
@a5hik thanks for the quick response!
