### ISSUE TITLE
directive name is too common

### ISSUE THREAD

**Issue by nebulaszlonemethi** [a5hik/ng-sortable#31]
Hi,
the directive name "sortable" is too common so it may easy collide with other directives uses the same attribute for their own markup, for example the popular grid component https://github.com/esvit/ng-table also applies the "sortable" attribute for the TD markup and therefore the two great extension doesn't work together.
A suggestion would be to add some "namespace" before the directive name, eg. a5hik-sortable or something.

**Comment by ivanrey** [comment]
It would be nice to use [Semantic Versioning](http://semver.org)   to avoid this kind of problems, since this update breaks the current code.
