### ISSUE TITLE
Drag and drop with scroll

### ISSUE THREAD

**Issue by Darex1991** [a5hik/ng-sortable#310]
Demo doesn't work.. http://a5hik.github.io/ng-sortable/#/scrollable
How to use it ;/?
![ng-sortable](https://cloud.githubusercontent.com/assets/5881611/14733109/b961e234-0860-11e6-911e-5172c56588c7.gif)

**Comment by lluiscanals** [comment]
It works if you scroll with the mouse wheel.

**Comment by Darex1991** [comment]
@lluiscanals 
![image](https://cloud.githubusercontent.com/assets/5881611/14733524/ee20c6b8-0863-11e6-80ff-1935421aec1c.png)

**Comment by rubyil** [comment]
+1 same problem here

**Comment by Darex1991** [comment]
I added https://github.com/malihu/malihu-custom-scrollbar-plugin and I pretends dragging scroll

**Comment by hafeezminhas** [comment]
I am facing the same issue on orderChanged. Using bootstrap as well. Any idea why this is happening? even the demo is not working. using malihu... ng-scrollbars
