### ISSUE TITLE
Cannot drag into empty list

### ISSUE THREAD

**Issue by bugjam** [a5hik/ng-sortable#311]
I'm using ng-sortable to drag and drop elements between two lists:
```
  <ul data-as-sortable="dragControlListeners" ng-model="listA">
    <li ng-repeat="t in listA" data-as-sortable-item data-as-sortable-item-handle>{{t}}</li>
  </ul>
  <ul data-as-sortable="dragControlListeners" ng-model="listB">
    <li ng-repeat="t in listB" data-as-sortable-item data-as-sortable-item-handle>{{t}}</li>
  </ul>
```
$scope.listA and $scope.listB are arrays of strings.
Now, this works fine as long as there are elements in both arrays. But if one array is empty, no placeholder is shown when trying to drag an element to that list.
I tried also configuring a placeholder as I figure the problem might be there is no &lt;li&gt; to clone - but I could not get that to work either.

Is this a bug or am I missing something?

**Comment by david12341235** [comment]
Try adding min-height to the list, eg `<ul style="min-height: 40px;" ...`

**Comment by bugjam** [comment]
Yes, that helped!
Thanks a lot for this and for a great library.

/Tore
Den 27/04/2016 03.17 skrev "david12341235" <notifications@github.com>:

**Comment by benjaminapetersen** [comment]
Closed issue? Or need documentation to close?

**Comment by a5hik** [comment]
Would be good to update the docs.
