### ISSUE TITLE
cant drag items 

### ISSUE THREAD

**Issue by sachilaRanawaka** [a5hik/ng-sortable#312]
hi. i'am trying to drag and drop items using ng-sortable. it works fine but dragging is not displaying visually. items cannot be drag visually from the page. 

![132b2n](https://cloud.githubusercontent.com/assets/16204359/14776140/0f169458-0ae2-11e6-8b7c-bac0b744f570.gif)
. 
this is the style sheet

```
/* ng-sortable css file */

.as-sortable-item,
.as-sortable-placeholder {
    display: block
}
.as-sortable-item {
    -ms-touch-action: none;
    touch-action: none;
    -webkit-touch-callout: none
}
.as-sortable-item-handle {
    cursor: move;
    cursor: -webkit-grab;
    cursor: -moz-grab
}
.as-sortable-drag {
    position: absolute;
    pointer-events: none;
    z-index: 9999
}
.as-sortable-hidden {
    display: none!important
}
.as-sortable-un-selectable {
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none
}

```

**Comment by Ronnnn** [comment]
Could you test if this pull request also fixes your issue?
https://github.com/a5hik/ng-sortable/pull/330

**Comment by johannesjo** [comment]
@Ronnnn I tried your fix, but unfortunately the issue still persists for me.
