### ISSUE TITLE
Drop to the specific place

### ISSUE THREAD

**Issue by Jeevanandanj** [a5hik/ng-sortable#314]
This is not the issue. I am asking how to implement for the following scenario.
**I am using ui router. **

**I've nested states (ParentController)**. Already I've implemented for the dragListeners1 for sorting and that's working fine.
**In Child state (ChildController)**, I've implemented the drag functionality.

Now I want to move the items from **dragListeners2 (child states)** to **dragListeners1 (parentstates)** but not from **dragListeners1 to dragListeners2** (This is happening now).

I cannot drag and drop the items from **dragListeners2 to dragListeners1** and I want to disable the sorting in **dragListeners2 **itself.

How can I do that?

LoggedInView
```
<!-- Parent state view -->
<div  data-ui-view>
  <div as-sortable="dragListeners1" ng-model="items1">
  </div>
<!-- Child state view -->
   <div data-ui-view>
        <div as-sortable="dragListeners2" ng-model='item2'>

        </div>
   </div>
</div>
```

**Comment by a5hik** [comment]
Plz refer the Docs and Demo code. Use the callbacks exposed.
