### ISSUE TITLE
sortable doesn't work when clone is true

### ISSUE THREAD

**Issue by torreant** [a5hik/ng-sortable#315]
hi all, in my scenario i would be able to sort items within a column A and clone items from column A to column B but if i set **clone: true** sortable doesn't work. With clone set to false it looks that item is moved so the user experience is not the best.

Do you have an hint about how solve it?

Thanks in advance

**Comment by a5hik** [comment]
@torreant this is by design the sorting is disabled on cloned items. we can take this as an enhancement request.
