### ISSUE TITLE
Disabling Debug data breaks ng-Sortable.

### ISSUE THREAD

**Issue by bosonau** [a5hik/ng-sortable#318]
following advice posted in https://docs.angularjs.org/guide/production for performance reasons
and running the main app with 
`myApp.config(['$compileProvider', function ($compileProvider) {
  $compileProvider.debugInfoEnabled(false);
}]);
 `
I found that any ng-sortable just fails to drag.  the classes are applied but that's it, no events are fired.

**Comment by a5hik** [comment]
@bosonau which version of ng-sortable you are using. By the way the demo version runs with debug info enabled set as 'false'.

**Comment by gitmh** [comment]
I can confirm this problem. I also tried to disable debug infos like @bosonau did and drag and drop stopped working. Just by commenting out the config line I can enable/disable drag and drop.

**Comment by a5hik** [comment]
Hi the demo and the latest code runs with debugInfoEnabled set to 'false' . I'm not sure what issue you are facing.

**Comment by VolleMelk** [comment]
Yeah.. I'm having the exact same problem
