### ISSUE TITLE
Items disappeared

### ISSUE THREAD

**Issue by solleOlle** [a5hik/ng-sortable#320]
I've found an [issue](https://www.dropbox.com/s/bcesleyeen9xfuy/as-sortable.ogv?dl=0) when an item is dragged on the bottom of a list, it's disappeared. 
I fixed it changing `this.source.modelValue` in the `dragItem.apply` function to `this.source.itemScope.value`

**NOTE**: please see a video by [clicking the link](https://www.dropbox.com/s/bcesleyeen9xfuy/as-sortable.ogv?dl=0) above

**Comment by a5hik** [comment]
@solleOlle are you using any filters in the sortable or track by?

**Comment by solleOlle** [comment]
Yes. I was using track by. Thanks

**Comment by a5hik** [comment]
@solleOlle it wont work properly with trackby. modifying applyItem is not recommended.
