### ISSUE TITLE
Plunker for showing Sortable

### ISSUE THREAD

**Issue by Sampath-Lokuge** [a5hik/ng-sortable#321]
Hi,
I need to create a Plunker for showing [**this functionality**](http://a5hik.github.io/ng-sortable/#/kanban).But I don't know how to get the `Views` for it.Could you give me a support for creating it ? Thanks.

This is what I have done so far [**Plunker**](https://plnkr.co/edit/U6TFQRR5JMoomCxIzgG7?p=preview)

**Comment by a5hik** [comment]
@Sampath-Lokuge how this is an issue?

**Comment by Sampath-Lokuge** [comment]
Can't you give any help for this @a5hik ? Thanks.
