### ISSUE TITLE
Firefox drag issue, still

### ISSUE THREAD

**Issue by vguna** [a5hik/ng-sortable#326]
Hi.

I'm using angular 1.4.8 together with ng-sortable 1.3.6 to provide reordering of a image collection. Also I use the latest firefox version. Using this combination I'm seeing the same effects as mentioned here: https://github.com/a5hik/ng-sortable/issues/61

I made a small gif that demonstrates the problem. If I try to drag the image, the no-drag-area sign appears and it doesn't start the drag operation. Also the dragStart callback isn't fired. When I release the mouse button, it automatically starts the drag operation as it should be and also the dragStart callback fires.

![img_drag](https://cloud.githubusercontent.com/assets/3257311/15632441/8f16e6ca-2591-11e6-90ca-6c2a83212ef6.gif)

It seems to have something todo with img tags. Using a normal div works as expected - like in the demos. Also using chrome is no problem with images.

Here's the code snippet:

```html
<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12">
		<ul id="image-collection" class="sort-horizontal" data-as-sortable="imageCollectionControlListeners" data-ng-model="hotel.images">
			<li data-ng-repeat="image in hotel.images" data-as-sortable-item>
				<div data-as-sortable-item-handle><img ng-src="{{image.url}}" style="border: 2px solid white; height: 100px" /></div>
			</li>
		</ul>
	</div>
</div>
```

If also read somewhere putting `draggable="false"` to the img tag should fix this. Indeed that seems to work most of the time. But even there, sometimes it fails as well. That happens, if I first select the image with a normal click. Then it selects the image with a blue overlay. If I try to drag that selected image, it fails the same way as without using `draggable=false`. Dragging an previously unselected image, works as expected.

![img_drag_draggable_false](https://cloud.githubusercontent.com/assets/3257311/15632497/f5f66e0e-2593-11e6-919c-11b950c88336.gif)

Any clue what's going on here?

**Comment by maniakill** [comment]
I had the same issue and the solution was to remove the image.
You can create a div with the width and height of the image and set the image as background with CSS
