### ISSUE TITLE
Problem with using directives.

### ISSUE THREAD

**Issue by delveintechnolabs** [a5hik/ng-sortable#327]
Hi,

I looked at the demos and liked it. Seemed to suit my requirements and has a plenty of options/callbacks. But there is an issue(may be particularly in my case)

What i have is something like this
```html
<div class="row">
 <div class="widget-parent" data-ng-repeat="widget in widgets">
  <directive-one data-ng-if="widget.items == 'one' ...some-other-attributes"></directive-one>
  <directive-two data-ng-if="widget.items == 'two' ...some-other-attributes"></directive-two>
  <directive-three data-ng-if="widget.items == 'three' ...some-other-attributes"></directive-three>
 </div>
</div>
```

the above directives are using templateURL(directive template in separate file)

I am not sure why i get error
`Uncaught TypeError: item.index is not a function`

NOTE : i have `as-sortable-item-handle` inside the directive template.

Can you please shed some light on why this directive might not work in above situation? 
I doubt two things.
- Due to isolated scope of my directive
- Due to ng-if(creating a child scope)

Thanks,
Hannan

**Comment by a5hik** [comment]
@delveintechnolabs there was a problem in using isolted scope inside a directive but that was fixed long back. refer #93 . 

Seems something might be wrong with the way you structure your directives. In the code snippet you provided I couldn't see any reference to any of sortable directives.
