### ISSUE TITLE
Item disappears when using ng-repeat with track by $index

### ISSUE THREAD

**Issue by jianwu** [a5hik/ng-sortable#328]
When I use ng-sortable with ng-repeat with "track by $index", for example:
`<div ng-repeat="img in images track by $index" data-as-sortable='sortOptions' data-ng-model='images'>
`

When I drag the item from position A to position B. Then do the reverse, from Position B to Postion A. 

The item B will be removed

**Comment by schystz** [comment]
I am experiencing the same issue. Once I removed `track by $index` it works perfectly fine. Any work around?

**Comment by joaohencke** [comment]
#299 

> a5hik commented on 21 May
the trackby will not work properly with ng-sortable. and this is documented.
