### ISSUE TITLE
Grid demo is broken

### ISSUE THREAD

**Issue by ValentinH** [a5hik/ng-sortable#333]
I just record a demo of the Grid as a GIF and as you can see, it's behaving weirdly:
![2016-07-20t13 06 10 851z](https://cloud.githubusercontent.com/assets/2678610/16987292/bdd39472-4e8b-11e6-99af-7ad432686d2d.gif)

**Comment by roger2hk** [comment]
I'm sorry but I don't really see the weird behavior.

**Comment by ValentinH** [comment]
The position of the bottom cells is unpredictable. I would expect them to align on the left and not to create new row at each move.

**Comment by jcroldan** [comment]
Your expected behavior must be implemented with one list of as-sortable-items. Instead it seems you are using 4 different lists that grows individually every time you drag and drop a new element.

**Comment by ValentinH** [comment]
This is a capture of the demo site of this library...

**Comment by ValentinH** [comment]
So this is working as expected?
