### ISSUE TITLE
dynamic data

### ISSUE THREAD

**Issue by Rainpia** [a5hik/ng-sortable#335]
when the list data is from database,need to change the list at any time.What should I do

**Comment by levainquer** [comment]
Try defining your own custom logic for the orderChanged() callback. 

Once you detect that your local copy of the data is changed, push the changed data back to the database.

**Comment by a5hik** [comment]
@Rainpia i don't see any problem with this case, as you can reset the list anytime. it doesn't affect the sort behaviour.
