### ISSUE TITLE
`event.source.itemScope` is undefined

### ISSUE THREAD

**Issue by matiishyn** [a5hik/ng-sortable#365]
Hi @a5hik 
thank you for the great Angular module.
We are using it in our project, but some time ago moving between columns stopped working. 
It turned out that inside `callbacks.itemMoved` method `event.source.itemScope` is undefined.

I thought it was my local problem so I cloned your repo (https://github.com/a5hik/ng-sortable#development-environment-setup) and you have the same problem in `demo/scripts/controllers/KanbanController.js:16` file:
![image](https://cloud.githubusercontent.com/assets/3661065/22082264/58dfe45a-ddc7-11e6-8dea-590d10daf49f.png)

![image](https://cloud.githubusercontent.com/assets/3661065/22082310/83f00530-ddc7-11e6-935c-c62595a9ca1b.png)

Could you please take a look.
Please let me know how can I fix it

Regards,
Ivan

**Comment by a5hik** [comment]
Hi I think this could be a problem introduced in some recent releases, can you try with a lower version. I'm sure this was not a problem in earlier versions.

**Comment by matiishyn** [comment]
yes, I think you are correct
because when I implemented this we had an earlier version and it definitely worked

I will try.
Thanks

**Comment by carsey** [comment]
Getting same issue. This commit broke it:
https://github.com/a5hik/ng-sortable/commit/29b56a14bad699b3007f0f56832677a6fdba3c3a

**Comment by matiishyn** [comment]
Reverting to the previous version `#1.3.6` fixed the issue.
Please whenever you fixed it in future releases please resolve this Github issue so I could get the update

**Comment by ruisilva450** [comment]
Getting the same issue here
@matiishyn `#1.3.6` is the most recent version and has this bug.
How did you reverted to the previous version?

**Comment by matiishyn** [comment]
@ruisilva450 
just put the `#1.3.6` in your `bower.json` and run `bower install` again
![image](https://cloud.githubusercontent.com/assets/3661065/24108802/02bdd45e-0d8f-11e7-8456-d79e3e5b5318.png)

**Comment by ruisilva450** [comment]
But that doesn't fix the problem, because I have the `#1.3.6` and I'm having this issue. 
Well, `#1.3.5` fixes it

**Comment by a5hik** [comment]
I had reverted the commit https://github.com/a5hik/ng-sortable/commit/29b56a14bad699b3007f0f56832677a6fdba3c3a in the latest version 1.3.8 . So it should be fixed in latest version.
