### ISSUE TITLE
Item positioning when start dragging.

### ISSUE THREAD

**Issue by dbrezoev** [a5hik/ng-sortable#368]
I have a strange issue, when dragging of an item just started, the draggable item jumps about 50px down and a few pixels right. So the cursor stays at nothing but actually drags the item. Any suggestions? Thanks in advance. EDIT: I noticed this is when I use the containment option. Without containment options is ok, but the draggable item doesnt have background.

**Comment by abhijitborade** [comment]
@dbrezoev How did you manage to fix this? I am getting same issue.
