### ISSUE TITLE
Scrollable and checkbox multiselect

### ISSUE THREAD

**Issue by maloparac** [a5hik/ng-sortable#4]
Is there any way to make column to be scrollable ? 

For example if i have 6 columns, it would be much easier if column can be scrollable so you can have like 5,6 cards and rest you can see when you scroll.
Then all of them would be visible on the screen

And check box on side and one for select all, for selecting multiple cards at once?

And thank you for this! :) You have done really great job!

**Comment by skchi** [comment]
Can we do multi-select? Please let me know if you have it.

**Comment by a5hik** [comment]
no we don't have this.
