### ISSUE TITLE
ng-sortable doesn't play nice with orderBy

### ISSUE THREAD

**Issue by amejiarosario** [a5hik/ng-sortable#53]
`todos = [{priority: 1, name: 'todo1'}, {priority: 2, name: 'todo2'}]`

Let's I want to orderBy priority... but every time I move an element I want the priority to be updated as well. Thus, the filter orderBy: 'priority' will revert the drag and drop changes... Any ideas to persist the new positions?

**Comment by fotofinder** [comment]
Would be nice to mention this in the docs.
