### ISSUE TITLE
Firefox drag issue

### ISSUE THREAD

**Issue by saffabook** [a5hik/ng-sortable#61]
Hi 

When using the drag and drop in chrome, it works beautifully, however when in firefox, it seems to misbehave. The issue is - when I click down and start moving, it doesnt seem to invoke the placeholders and shift the images around. When I release the mouse click then it all seems to what is suppose to happen when the mouse is down. I think it has something to do with the 10px check. What I did was take the `dragStart(event);` out of the`var moveListen = function ...` function and it all seems to work in FF now. This is around line 593 in the ng-sortable.js file. 

I loose out on the 10px detect but for me that is not an issue. Just thought I would raise it with you. 

I am still new to angular too, so my knowledge is very limited, thanks for a great plugin.

**Comment by YooTanya** [comment]
@saffabook Could u please tell me how do you fix it? I am facing the same problem on firefox and safari too.

**Comment by DonHaron** [comment]
I have been encountering the same problem in Firefox as saffabook first wrote:

>  The issue is - when I click down and start moving, it doesnt seem to invoke the placeholders and shift the images around. When I release the mouse click then it all seems to what is suppose to happen when the mouse is down.

I have only been encountering this problem when I used an anchor tag (<a>) as the drag handle. When I use a div instead everything works fine. Firefox probably handles the drag event a bit differently there. Posting this here for if anyone else has the problem

**Comment by peterjhart** [comment]
You can also use `ng-mousedown="$event.preventDefault()"` on the element that has the as-sortable-item-handle.

**Comment by elialbert** [comment]
coming back in 2019 to mention that @peterjhart 's comment still fixes firefox for me.
