### ISSUE TITLE
Dragging items causes selection of text

### ISSUE THREAD

**Issue by steve-tapley** [a5hik/ng-sortable#74]
Hi,
In the plunkr at http://plnkr.co/edit/GtdBgPxXHjSRHvl9st1A?p=preview and you can see when dragging the item, that selection artifacts appear when dragging.

This happens on FF 33.1.1 (and 32.x), IE 11.

I've put some styling on the item handle (height=50px) - NOTE, I've only put this on there to make the issue easier to reproduce - it fails on FF consistently without this additional styling.

On IE, if you drag the item near the edge of its container, it will (on most attempts) select some text in some of the other items.

I'll keep looking into it, but if you have any ideas, please let me know.

Thanks,
Steve

**Comment by cmhand** [comment]
@SkylerLipthay Does your fix work in IE11? I've tried implementing it and I still get text selection.

If I manually add the class to the body tag, it works as expected and nothing can be selected. However if I use your code above or some variation that adds the class at the beginning of the drag, the class is successfully added, but no element besides the body tag gets the computed style.

If anyone has any fixes, I'd love to hear.

**Comment by a5hik** [comment]
the proposed changes were committed in to core.

**Comment by fotofinder** [comment]
As the user-select property is not standard and has to use all these browser prefixes,
marking the sortable-item as ``draggable``might be an option.
``<div draggable="true"   ng-repeat="item in items" as-sortable-item>``
It is sufficient to mention this in the documentation. No need for code changes.
It is 'experimental' too, but works for me on the 'modern browsers'.


https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable
https://developer.mozilla.org/en-US/docs/Web/CSS/user-select

**Comment by Gargaroz** [comment]
Hi, I'm still experiencing this issue in IE11. I have the latest version installed and the issue it's still there even if I apply the fix given by @SkylerLipthay .
