### ISSUE TITLE
Autoscroll, programmatically triggering a method set / update position

### ISSUE THREAD

**Issue by dnmd** [a5hik/ng-sortable#82]
I noticed #9 by @ivanrey and #13 by @glook, and also read your reply stating that one could control autoscroll via (the) a Container Control. When implementing autoscroll (up/down) via e.g.
```javascript
setInterval(function(){
 container.scrollTop = step++ / --;
}, 25);
```
 the drag event (and consequently the [moveposition](https://github.com/a5hik/ng-sortable/blob/master/dist/ng-sortable.js#L207) method will (of course) not fire, and thus slowly displacing the dragged element, since the last "top" position is stored right before the setInterval is triggered.
- Do you see another method for scrolling down / up than using setInterval?
- Do you see a possibility to expose a method to trigger / set / update the (top) position? Or i.e. to initiate a self drag offset (+/-)?

**Comment by a5hik** [comment]
the #13 has solution, hence closing this.
