### ISSUE TITLE
Uncaught HierarchyRequestError: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.

### ISSUE THREAD

**Issue by Gillardo** [a5hik/ng-sortable#88]
I am getting this error when i start to move an item.  It appears when you just move the item over the place where the item already was, then if you move the cursor away from that area and go back to it, the error disappears.  It appears to happen if the place your moving the item from only has 1 item and this is the item you are moving, thus there would be no items left in that list

Also...
On my page i have 2 types of lists, one for groups and one for fields.  Now i dont want the user to be able to drag a field into a group, not a group into a field.

Is there a way to stop this happening?  In the jquery-ui version, you can state a placeholder that the items should be allowed to drop into, is this available here?

**Comment by RickCarlino** [comment]
Hi guys-

I hit this issue today also. Am I following the correct order?

```html
<div>
  <div ng-repeat='step in sequence.steps | orderBy: "position" '>
    <div as-sortable-item ng-model="step">
      Content here...
    </div>
  </div>
</div>
```

**Comment by coldasflux** [comment]
I run into the same error having images in `as-sortable-item-handler` and `as-sortable-placeholder` container. Setting `pointer-events: none` for the img (oddly) fixed the issue for me.

**Comment by kishankanugula** [comment]
I am trying to use this library for tables. It works well but seeing "Uncaught HierarchyRequestError: Failed to execute 'appendChild' on 'Node': The new child element contains the parent." in console. Is having ng-repeat straight after as-sortable is mandatory?.

**Comment by a5hik** [comment]
@kishankanugula I do not think any order is mandatory here. are you placing any filters on the sortables? eg . orderBy etc.

**Comment by kishankanugula** [comment]
@a5hik I have created a plunker for you 
http://plnkr.co/edit/J9qa56idF2vhRZ96UqLA?p=preview
There's no problem with drag and drop but if you see the console it shows the "Uncaught HierarchyRequestError: Failed to execute 'appendChild' on 'Node': The new child element contains the parent." and this shows for every move.  Let me know if i am doing something wrong?

**Comment by a5hik** [comment]
@kishankanugula I tested the plunker and changing from 'table' to 'ul li' fixed the issue.

However also provided an other fix related to this. But couldn't get much time to figure out the root cause.
You can proceed with changing your html structure with 'ul li' based one instead of using 'table'.

**Comment by VarshilDoshi** [comment]
i am also get this type of exception..
ERROR DOMException: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.
what can i do??
