### ISSUE TITLE
Drag & Drop doesn't work when window or container has scroll

### ISSUE THREAD

**Issue by meassinal** [a5hik/ng-sortable#91]
I have tested this library for a while I feel most part of it is working really well; but when I have been asked if it works in scrollable container. Since then I tried again with this scenario. Yes it seemed work quite well in firefox, but didn't in chrome. I also looked into source code I came across this variable <code>scrollableContainer</code> and still didn't work. Could any body here point out a solution to this?

**Comment by neagle** [comment]
I've added an example of my running into what looks like the same bug. First it shows two sortable lists behaving beautifully. Then I decrease the window size to create a scroll bar, and suddenly the dragged items jump as soon as I click on them.

![ng-sortable-bug](https://cloud.githubusercontent.com/assets/176993/6275928/0e365c38-b851-11e4-8d9c-f5fafdf8506e.gif)

**Comment by a5hik** [comment]
Hi what kind of error you see in the browser console?

**Comment by wk-cof** [comment]
@a5hik, there is no error. I think Chrome ignores the scroll screen offset.
E.g. if the element is at x=100px on the screen and the screen is scrolled to 200px, FireFox and IE 11 will correctly identify that the element is actually at 300px, while Chrome will continue to think that it's at 100px.

**Comment by wk-cof** [comment]
@meassinal and @Serhioromano: I ended up solving my issue by having scroll within the element rather than using browser scroll. E.g. <div class="container-fluid" style="overflow-x: scroll">

This doesn't address the underlying issue but it makes the library usable when you need lateral scroll.
Hope that helps.
