### ISSUE TITLE
it is not working with debug off

### ISSUE THREAD

**Issue by Serhioromano** [a5hik/ng-sortable#92]
Hello,

While I am developing i am using `$compileProvider.debugInfoEnabled(true);` but when publish to production I use `$compileProvider.debugInfoEnabled(false);`. This increase speed of application and absolutely important to me to use. I do not what also customers to see errors.

I spent more than 2 hours to find out why my deploy is not working. I use `gulp` and I build application by concatenating all JS and CSS files, cleaning some directories, ... So my 2Mb project endup 400kb not gziped. 

This is not the point, the point is that I thought there is a problem during minifications. So I spent a lot of time to debug while I found this one. And to me it does not make any sense why this parameter would make any difference.

**Comment by MaitreDede** [comment]
At the line 710 of the unminified script :
```
sourceScope = elementClicked.scope();
```
When ```$compileProvider.debugInfoEnabled(true)``` sourceScope is filled, when ```$compileProvider.debugInfoEnabled(false)``` sourceScope is null. So element is considered "non draggable"

**Comment by MaitreDede** [comment]
https://docs.angularjs.org/api/ng/function/angular.element :
> scope() - retrieves the scope of the current element or its parent. Requires Debug Data to be enabled.

**Comment by MaitreDede** [comment]
In the ```mainModule.directive('asSortableItemHandle', ['```, why not adding a ```$scope``` dependency ?

**Comment by adamalbrecht** [comment]
+1 Just ran into this

**Comment by maximilianschmid** [comment]
+1 I have experienced this bug too.

**Comment by a5hik** [comment]
this is tracked via #71 hence closing.
