### ISSUE TITLE
Using table and rows instead of un ordered list

### ISSUE THREAD

**Issue by shyamveerapally** [a5hik/ng-sortable#96]
Hi,
     I tried to use this with table and rows instead of UL/LI. The drag and drop effect is not working smooth and could see flicker. Is there a way to use table rather than using styles on UL for table look?

Also, is it feasible to drag and drop consecutive elements?

Thanks,
Shyam

**Comment by kostjerry** [comment]
+1. I have the same problem: drag and drop process looks awful in tables.

**Comment by MarkySparky** [comment]
Same here. Would be good to get this solved. Tables are flicking every other pixel.

**Comment by nilskaspersson** [comment]
It sounds like you're applying `as-sortable` to the `<table>` and not to the `<tbody>`.

**Comment by msTokenizer** [comment]
+1 to make tables work out of the box (Thx for the lib, it's really nice)
